UpdateBlogImagePayload:
    type: relay-mutation-payload
    config:
        fields:
            siteImage:
                type: 'SiteImage'
            errorCode:
                type: 'UpdateBlogImageErrorCode'
