UpdateBlogSettingPayload:
    type: relay-mutation-payload
    config:
        fields:
            siteParameter:
                type: 'SiteParameter'
            errorCode:
                type: 'UpdateBlogSettingErrorCode'
