CreateNewsletterSubscriptionInput:
    type: relay-mutation-input
    config:
        description: 'Input of createNewsletterSubscription mutation.'
        fields:
            email:
                type: 'String!'
                description: 'The email to subscribe.'
            isEnabled:
                type: 'Boolean!'
                description: 'Whether the email is subscribed to the newsletter.'
