<?php

namespace Capco\AppBundle\Toggle;

class EnvironmentPresets
{
    public const COMMON = [
        Manager::analytics_page,
        Manager::blog,
        Manager::calendar,
        Manager::captcha,
        Manager::consultation_plan,
        Manager::display_map,
        Manager::display_pictures_in_depository_proposals_list,
        Manager::display_pictures_in_event_list,
        Manager::districts,
        Manager::emailing,
        Manager::emailing_group,
        Manager::emailing_parameters,
        Manager::graphql_introspection,
        Manager::http_redirects,
        Manager::import_proposals,
        Manager::indexation,
        Manager::paper_vote,
        Manager::privacy_policy,
        Manager::profiles,
        Manager::proposal_revisions,
        Manager::questionnaire_result,
        Manager::themes,
        Manager::turnstile_captcha,
        Manager::unstable__new_create_project,
        Manager::votes_min,
    ];

    public const PROD = [
        ...self::COMMON,
        Manager::export,
        Manager::members_list,
        Manager::multi_consultations,
        Manager::new_project_card,
        Manager::newsletter,
        Manager::noindex_on_profiles,
        Manager::online_help,
        Manager::phone_confirmation,
        Manager::report_browers_errors_to_sentry,
        Manager::reporting,
        Manager::restrict_connection,
        Manager::secure_password,
        Manager::sentry_log,
        Manager::share_buttons,
        Manager::twilio,
    ];

    public const TEST = [
        ...self::COMMON,
        Manager::consent_internal_communication,
        Manager::developer_documentation,
        Manager::export,
        Manager::external_project,
        Manager::login_facebook,
        Manager::mailjet_sandbox,
        Manager::mediator,
        Manager::members_list,
        Manager::multi_consultations,
        Manager::multilangue,
        Manager::new_project_card,
        Manager::newsletter,
        Manager::organizations,
        Manager::project_admin,
        Manager::project_trash,
        Manager::projects_form,
        Manager::public_api,
        Manager::registration,
        Manager::remind_user_account_confirmation,
        Manager::reporting,
        Manager::search,
        Manager::server_side_rendering,
        Manager::share_buttons,
        Manager::user_type,
        Manager::versions,
    ];

    public const DEV = [
        ...self::COMMON,
        Manager::antivirus,
        Manager::consent_internal_communication,
        Manager::developer_documentation,
        Manager::login_cas,
        Manager::login_facebook,
        Manager::login_franceconnect,
        Manager::login_openid,
        Manager::login_saml,
        Manager::mailjet_sandbox,
        Manager::mediator,
        Manager::multilangue,
        Manager::organizations,
        Manager::project_admin,
        Manager::project_trash,
        Manager::public_api,
        Manager::registration,
        Manager::remind_user_account_confirmation,
        Manager::user_type,
        Manager::versions,
    ];
}
