module.exports = {
  // To Enable persisted queries:
  // persistOutput: "./queryMap.json",
  src: './',
  noFutureProofEnums: true,
  language: 'typescript',
  schema: './schema.internal.graphql',
  artifactDirectory: './frontend/js/__generated__/~relay',
  exclude: [
    '**/node_modules/**',
    '**/__mocks__/**',
    '**/__generated__/**',
    '**/admin-next/components/**',
    '**/admin-next/mutations/**',
    '**/admin-next/hooks/**',
    '**/admin-next/pages/**',
    '**/admin-next/utils/**',
    '**/schema.public.graphql',
    '**/schema.dev.graphql',
    '**/schema.preview.graphql',
    '**/admin-next/src/**',
  ],
  customScalars: {
    DateTime: 'string',
    Email: 'string',
    URI: 'string',
    IP: 'string',
    Address: 'string',
    JSON: 'string',
    HTML: 'string',
    Color: 'string',
    CssJSON: 'string',
    GeoJSON: 'string',
  },
}
