#!/bin/bash

while ! ps -ef | grep php-fpm > /dev/null 2>&1;
  do sleep 0.1
  echo "Waiting for PHP FPM to start..."
done

echo "Launching Supervisord..."
exec supervisord --nodaemon --configuration=/etc/supervisord/supervisord.conf
