// flow-typed signature: b91ab99aee7be6a7f67d2cfad6b7d2fa
// flow-typed version: <<STUB>>/babel-plugin-react-display-name_v^2.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-display-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-display-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-react-display-name/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-react-display-name/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-display-name/lib/index'>;
}
