// flow-typed signature: f8753a3116bb8ca4f8d944eaa5778775
// flow-typed version: <<STUB>>/babel-brunch_v^6.1.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-brunch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-brunch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'babel-brunch/index' {
  declare module.exports: $Exports<'babel-brunch'>;
}
declare module 'babel-brunch/index.js' {
  declare module.exports: $Exports<'babel-brunch'>;
}
