// flow-typed signature: 36a20de98ef3de81818f3c06ed465e74
// flow-typed version: <<STUB>>/autosize_v^3.0.15/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'autosize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'commander' {
  declare module.exports: any;
}
