// flow-typed signature: 364927e734ff42fd1d9a2494174bbb55
// flow-typed version: <<STUB>>/draft-js-export-html_v1.4.1/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-export-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-export-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-export-html/esm/__tests__/stateToHTML-test' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/esm/helpers/__tests__/combineOrderedStyles-test' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/esm/helpers/__tests__/normalizeAttributes-test' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/esm/helpers/__tests__/styleToCSS-test' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/esm/helpers/combineOrderedStyles' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/esm/helpers/normalizeAttributes' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/esm/helpers/styleToCSS' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/esm/main' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/esm/stateToHTML' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/lib/__tests__/stateToHTML-test' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/lib/helpers/__tests__/combineOrderedStyles-test' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/lib/helpers/__tests__/normalizeAttributes-test' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/lib/helpers/__tests__/styleToCSS-test' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/lib/helpers/combineOrderedStyles' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/lib/helpers/normalizeAttributes' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/lib/helpers/styleToCSS' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/lib/main' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/lib/stateToHTML' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-export-html/esm/__tests__/stateToHTML-test.js' {
  declare module.exports: $Exports<'draft-js-export-html/esm/__tests__/stateToHTML-test'>;
}
declare module 'draft-js-export-html/esm/helpers/__tests__/combineOrderedStyles-test.js' {
  declare module.exports: $Exports<'draft-js-export-html/esm/helpers/__tests__/combineOrderedStyles-test'>;
}
declare module 'draft-js-export-html/esm/helpers/__tests__/normalizeAttributes-test.js' {
  declare module.exports: $Exports<'draft-js-export-html/esm/helpers/__tests__/normalizeAttributes-test'>;
}
declare module 'draft-js-export-html/esm/helpers/__tests__/styleToCSS-test.js' {
  declare module.exports: $Exports<'draft-js-export-html/esm/helpers/__tests__/styleToCSS-test'>;
}
declare module 'draft-js-export-html/esm/helpers/combineOrderedStyles.js' {
  declare module.exports: $Exports<'draft-js-export-html/esm/helpers/combineOrderedStyles'>;
}
declare module 'draft-js-export-html/esm/helpers/normalizeAttributes.js' {
  declare module.exports: $Exports<'draft-js-export-html/esm/helpers/normalizeAttributes'>;
}
declare module 'draft-js-export-html/esm/helpers/styleToCSS.js' {
  declare module.exports: $Exports<'draft-js-export-html/esm/helpers/styleToCSS'>;
}
declare module 'draft-js-export-html/esm/main.js' {
  declare module.exports: $Exports<'draft-js-export-html/esm/main'>;
}
declare module 'draft-js-export-html/esm/stateToHTML.js' {
  declare module.exports: $Exports<'draft-js-export-html/esm/stateToHTML'>;
}
declare module 'draft-js-export-html/lib/__tests__/stateToHTML-test.js' {
  declare module.exports: $Exports<'draft-js-export-html/lib/__tests__/stateToHTML-test'>;
}
declare module 'draft-js-export-html/lib/helpers/__tests__/combineOrderedStyles-test.js' {
  declare module.exports: $Exports<'draft-js-export-html/lib/helpers/__tests__/combineOrderedStyles-test'>;
}
declare module 'draft-js-export-html/lib/helpers/__tests__/normalizeAttributes-test.js' {
  declare module.exports: $Exports<'draft-js-export-html/lib/helpers/__tests__/normalizeAttributes-test'>;
}
declare module 'draft-js-export-html/lib/helpers/__tests__/styleToCSS-test.js' {
  declare module.exports: $Exports<'draft-js-export-html/lib/helpers/__tests__/styleToCSS-test'>;
}
declare module 'draft-js-export-html/lib/helpers/combineOrderedStyles.js' {
  declare module.exports: $Exports<'draft-js-export-html/lib/helpers/combineOrderedStyles'>;
}
declare module 'draft-js-export-html/lib/helpers/normalizeAttributes.js' {
  declare module.exports: $Exports<'draft-js-export-html/lib/helpers/normalizeAttributes'>;
}
declare module 'draft-js-export-html/lib/helpers/styleToCSS.js' {
  declare module.exports: $Exports<'draft-js-export-html/lib/helpers/styleToCSS'>;
}
declare module 'draft-js-export-html/lib/main.js' {
  declare module.exports: $Exports<'draft-js-export-html/lib/main'>;
}
declare module 'draft-js-export-html/lib/stateToHTML.js' {
  declare module.exports: $Exports<'draft-js-export-html/lib/stateToHTML'>;
}
