// flow-typed signature: 35dc7236f8a9f06aa065d659e52d3ba8
// flow-typed version: <<STUB>>/eslint-plugin-jest_v^1.0.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-jest/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/no-exclusive-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/__tests__/no-identical-title' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/no-exclusive-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/lib/rules/no-identical-title' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-jest/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/index'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/no-exclusive-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/no-exclusive-tests'>;
}
declare module 'eslint-plugin-jest/lib/rules/__tests__/no-identical-title.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/__tests__/no-identical-title'>;
}
declare module 'eslint-plugin-jest/lib/rules/no-exclusive-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/no-exclusive-tests'>;
}
declare module 'eslint-plugin-jest/lib/rules/no-identical-title.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/lib/rules/no-identical-title'>;
}
