// flow-typed signature: ae73a273ed5b0cda568760872ef1ad2a
// flow-typed version: <<STUB>>/flat_v^2.0.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'flat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flat/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flat/index' {
  declare module.exports: $Exports<'flat'>;
}
declare module 'flat/index.js' {
  declare module.exports: $Exports<'flat'>;
}
declare module 'flat/test/test.js' {
  declare module.exports: $Exports<'flat/test/test'>;
}
