// flow-typed signature: 37370b68604871f7c66d6ed28b76bfc7
// flow-typed version: <<STUB>>/javascript-brunch_v^2.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'javascript-brunch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'javascript-brunch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'javascript-brunch/index' {
  declare module.exports: $Exports<'javascript-brunch'>;
}
declare module 'javascript-brunch/index.js' {
  declare module.exports: $Exports<'javascript-brunch'>;
}
