// flow-typed signature: c7572c2fb870d4517573c5ffed721757
// flow-typed version: <<STUB>>/json-brunch_v^1.5.4/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-brunch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-brunch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-brunch/lib/index' {
  declare module.exports: any;
}

declare module 'json-brunch/setup' {
  declare module.exports: any;
}

declare module 'json-brunch/test/common' {
  declare module.exports: any;
}

declare module 'json-brunch/test/plugin_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-brunch/lib/index.js' {
  declare module.exports: $Exports<'json-brunch/lib/index'>;
}
declare module 'json-brunch/setup.js' {
  declare module.exports: $Exports<'json-brunch/setup'>;
}
declare module 'json-brunch/test/common.js' {
  declare module.exports: $Exports<'json-brunch/test/common'>;
}
declare module 'json-brunch/test/plugin_test.js' {
  declare module.exports: $Exports<'json-brunch/test/plugin_test'>;
}
