// flow-typed signature: bceef5ce5348087f85e6aa5d2738cb9d
// flow-typed version: <<STUB>>/mailcheck_v^1.1.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mailcheck'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mailcheck' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mailcheck/script/server' {
  declare module.exports: any;
}

declare module 'mailcheck/spec/lib/console-runner' {
  declare module.exports: any;
}

declare module 'mailcheck/spec/lib/jasmine-1.2.0/jasmine-html' {
  declare module.exports: any;
}

declare module 'mailcheck/spec/lib/jasmine-1.2.0/jasmine' {
  declare module.exports: any;
}

declare module 'mailcheck/spec/lib/jquery' {
  declare module.exports: any;
}

declare module 'mailcheck/spec/mailcheckSpec' {
  declare module.exports: any;
}

declare module 'mailcheck/src/mailcheck' {
  declare module.exports: any;
}

declare module 'mailcheck/src/mailcheck.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mailcheck/script/server.js' {
  declare module.exports: $Exports<'mailcheck/script/server'>;
}
declare module 'mailcheck/spec/lib/console-runner.js' {
  declare module.exports: $Exports<'mailcheck/spec/lib/console-runner'>;
}
declare module 'mailcheck/spec/lib/jasmine-1.2.0/jasmine-html.js' {
  declare module.exports: $Exports<'mailcheck/spec/lib/jasmine-1.2.0/jasmine-html'>;
}
declare module 'mailcheck/spec/lib/jasmine-1.2.0/jasmine.js' {
  declare module.exports: $Exports<'mailcheck/spec/lib/jasmine-1.2.0/jasmine'>;
}
declare module 'mailcheck/spec/lib/jquery.js' {
  declare module.exports: $Exports<'mailcheck/spec/lib/jquery'>;
}
declare module 'mailcheck/spec/mailcheckSpec.js' {
  declare module.exports: $Exports<'mailcheck/spec/mailcheckSpec'>;
}
declare module 'mailcheck/src/mailcheck.js' {
  declare module.exports: $Exports<'mailcheck/src/mailcheck'>;
}
declare module 'mailcheck/src/mailcheck.min.js' {
  declare module.exports: $Exports<'mailcheck/src/mailcheck.min'>;
}
