// flow-typed signature: a0200a7990526157edc6c737ef6c5db9
// flow-typed version: <<STUB>>/points-cluster_v^0.1.4/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'points-cluster'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'points-cluster' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'points-cluster/lib/index' {
  declare module.exports: any;
}

declare module 'points-cluster/lib/utils/createTree' {
  declare module.exports: any;
}

declare module 'points-cluster/lib/utils/latLng' {
  declare module.exports: any;
}

// Filename aliases
declare module 'points-cluster/lib/index.js' {
  declare module.exports: $Exports<'points-cluster/lib/index'>;
}
declare module 'points-cluster/lib/utils/createTree.js' {
  declare module.exports: $Exports<'points-cluster/lib/utils/createTree'>;
}
declare module 'points-cluster/lib/utils/latLng.js' {
  declare module.exports: $Exports<'points-cluster/lib/utils/latLng'>;
}
