// flow-typed signature: 6ad663b3f354a142b6c997398ba3a13b
// flow-typed version: <<STUB>>/process-env-brunch_v^1.4.4-d/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'process-env-brunch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'process-env-brunch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'process-env-brunch/grunt' {
  declare module.exports: any;
}

declare module 'process-env-brunch/lib/index' {
  declare module.exports: any;
}

declare module 'process-env-brunch/setup' {
  declare module.exports: any;
}

declare module 'process-env-brunch/test/index_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'process-env-brunch/grunt.js' {
  declare module.exports: $Exports<'process-env-brunch/grunt'>;
}
declare module 'process-env-brunch/lib/index.js' {
  declare module.exports: $Exports<'process-env-brunch/lib/index'>;
}
declare module 'process-env-brunch/setup.js' {
  declare module.exports: $Exports<'process-env-brunch/setup'>;
}
declare module 'process-env-brunch/test/index_test.js' {
  declare module.exports: $Exports<'process-env-brunch/test/index_test'>;
}
