// flow-typed signature: ccb5d91ea9e511a1cdcbc3d3576916fe
// flow-typed version: <<STUB>>/react-leaflet-markercluster_vhttps://github.com/cap-collectif/react-leaflet-markercluster/tarball/2d91878f0bd99af7a5352050315a50b4c4c4bf34/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-leaflet-markercluster'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-leaflet-markercluster' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-leaflet-markercluster/demo-app/components/basic-example/example-one' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/components/basic-example/example-two' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/components/basic-example/index' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/components/custom-options/example-one' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/components/custom-options/example-two' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/components/custom-options/index' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/components/event-listeners/example-one' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/components/event-listeners/index' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/components/marker-options/example-one' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/components/marker-options/example-two' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/components/marker-options/index' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/components/marker-popup/example-one' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/components/marker-popup/index' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/components/marker-tooltip/example-one' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/components/marker-tooltip/index' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/components/markercluster-options/example-one' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/components/markercluster-options/index' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/constants' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/containers/welcome-page' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/demo-app/main' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/dist/react-leaflet-markercluster' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/dist/react-leaflet-markercluster.min' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/src/react-leaflet-markercluster' {
  declare module.exports: any;
}

declare module 'react-leaflet-markercluster/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-leaflet-markercluster/demo-app/components/basic-example/example-one.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/components/basic-example/example-one'>;
}
declare module 'react-leaflet-markercluster/demo-app/components/basic-example/example-two.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/components/basic-example/example-two'>;
}
declare module 'react-leaflet-markercluster/demo-app/components/basic-example/index.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/components/basic-example/index'>;
}
declare module 'react-leaflet-markercluster/demo-app/components/custom-options/example-one.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/components/custom-options/example-one'>;
}
declare module 'react-leaflet-markercluster/demo-app/components/custom-options/example-two.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/components/custom-options/example-two'>;
}
declare module 'react-leaflet-markercluster/demo-app/components/custom-options/index.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/components/custom-options/index'>;
}
declare module 'react-leaflet-markercluster/demo-app/components/event-listeners/example-one.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/components/event-listeners/example-one'>;
}
declare module 'react-leaflet-markercluster/demo-app/components/event-listeners/index.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/components/event-listeners/index'>;
}
declare module 'react-leaflet-markercluster/demo-app/components/marker-options/example-one.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/components/marker-options/example-one'>;
}
declare module 'react-leaflet-markercluster/demo-app/components/marker-options/example-two.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/components/marker-options/example-two'>;
}
declare module 'react-leaflet-markercluster/demo-app/components/marker-options/index.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/components/marker-options/index'>;
}
declare module 'react-leaflet-markercluster/demo-app/components/marker-popup/example-one.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/components/marker-popup/example-one'>;
}
declare module 'react-leaflet-markercluster/demo-app/components/marker-popup/index.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/components/marker-popup/index'>;
}
declare module 'react-leaflet-markercluster/demo-app/components/marker-tooltip/example-one.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/components/marker-tooltip/example-one'>;
}
declare module 'react-leaflet-markercluster/demo-app/components/marker-tooltip/index.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/components/marker-tooltip/index'>;
}
declare module 'react-leaflet-markercluster/demo-app/components/markercluster-options/example-one.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/components/markercluster-options/example-one'>;
}
declare module 'react-leaflet-markercluster/demo-app/components/markercluster-options/index.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/components/markercluster-options/index'>;
}
declare module 'react-leaflet-markercluster/demo-app/constants.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/constants'>;
}
declare module 'react-leaflet-markercluster/demo-app/containers/welcome-page.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/containers/welcome-page'>;
}
declare module 'react-leaflet-markercluster/demo-app/main.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/demo-app/main'>;
}
declare module 'react-leaflet-markercluster/dist/react-leaflet-markercluster.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/dist/react-leaflet-markercluster'>;
}
declare module 'react-leaflet-markercluster/dist/react-leaflet-markercluster.min.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/dist/react-leaflet-markercluster.min'>;
}
declare module 'react-leaflet-markercluster/gulpfile.babel.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/gulpfile.babel'>;
}
declare module 'react-leaflet-markercluster/src/react-leaflet-markercluster.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/src/react-leaflet-markercluster'>;
}
declare module 'react-leaflet-markercluster/webpack.config.js' {
  declare module.exports: $Exports<'react-leaflet-markercluster/webpack.config'>;
}
