// flow-typed signature: 4910fc34217385c5745e91c246f4443a
// flow-typed version: <<STUB>>/react-on-rails_v^6.3.2/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-on-rails'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-on-rails' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-on-rails/node_package/lib/Authenticity' {
  declare module.exports: any;
}

declare module 'react-on-rails/node_package/lib/buildConsoleReplay' {
  declare module.exports: any;
}

declare module 'react-on-rails/node_package/lib/clientStartup' {
  declare module.exports: any;
}

declare module 'react-on-rails/node_package/lib/ComponentRegistry' {
  declare module.exports: any;
}

declare module 'react-on-rails/node_package/lib/context' {
  declare module.exports: any;
}

declare module 'react-on-rails/node_package/lib/createReactElement' {
  declare module.exports: any;
}

declare module 'react-on-rails/node_package/lib/generatorFunction' {
  declare module.exports: any;
}

declare module 'react-on-rails/node_package/lib/handleError' {
  declare module.exports: any;
}

declare module 'react-on-rails/node_package/lib/isRouterResult' {
  declare module.exports: any;
}

declare module 'react-on-rails/node_package/lib/ReactOnRails' {
  declare module.exports: any;
}

declare module 'react-on-rails/node_package/lib/RenderUtils' {
  declare module.exports: any;
}

declare module 'react-on-rails/node_package/lib/scriptSanitizedVal' {
  declare module.exports: any;
}

declare module 'react-on-rails/node_package/lib/serverRenderReactComponent' {
  declare module.exports: any;
}

declare module 'react-on-rails/node_package/lib/StoreRegistry' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-on-rails/node_package/lib/Authenticity.js' {
  declare module.exports: $Exports<'react-on-rails/node_package/lib/Authenticity'>;
}
declare module 'react-on-rails/node_package/lib/buildConsoleReplay.js' {
  declare module.exports: $Exports<'react-on-rails/node_package/lib/buildConsoleReplay'>;
}
declare module 'react-on-rails/node_package/lib/clientStartup.js' {
  declare module.exports: $Exports<'react-on-rails/node_package/lib/clientStartup'>;
}
declare module 'react-on-rails/node_package/lib/ComponentRegistry.js' {
  declare module.exports: $Exports<'react-on-rails/node_package/lib/ComponentRegistry'>;
}
declare module 'react-on-rails/node_package/lib/context.js' {
  declare module.exports: $Exports<'react-on-rails/node_package/lib/context'>;
}
declare module 'react-on-rails/node_package/lib/createReactElement.js' {
  declare module.exports: $Exports<'react-on-rails/node_package/lib/createReactElement'>;
}
declare module 'react-on-rails/node_package/lib/generatorFunction.js' {
  declare module.exports: $Exports<'react-on-rails/node_package/lib/generatorFunction'>;
}
declare module 'react-on-rails/node_package/lib/handleError.js' {
  declare module.exports: $Exports<'react-on-rails/node_package/lib/handleError'>;
}
declare module 'react-on-rails/node_package/lib/isRouterResult.js' {
  declare module.exports: $Exports<'react-on-rails/node_package/lib/isRouterResult'>;
}
declare module 'react-on-rails/node_package/lib/ReactOnRails.js' {
  declare module.exports: $Exports<'react-on-rails/node_package/lib/ReactOnRails'>;
}
declare module 'react-on-rails/node_package/lib/RenderUtils.js' {
  declare module.exports: $Exports<'react-on-rails/node_package/lib/RenderUtils'>;
}
declare module 'react-on-rails/node_package/lib/scriptSanitizedVal.js' {
  declare module.exports: $Exports<'react-on-rails/node_package/lib/scriptSanitizedVal'>;
}
declare module 'react-on-rails/node_package/lib/serverRenderReactComponent.js' {
  declare module.exports: $Exports<'react-on-rails/node_package/lib/serverRenderReactComponent'>;
}
declare module 'react-on-rails/node_package/lib/StoreRegistry.js' {
  declare module.exports: $Exports<'react-on-rails/node_package/lib/StoreRegistry'>;
}
