// flow-typed signature: c7dc71a72bd407c5fd6d4327f1e09aad
// flow-typed version: <<STUB>>/react-radio-buttons_v^1.0.11/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-radio-buttons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-radio-buttons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-radio-buttons/lib/index' {
  declare module.exports: any;
}

declare module 'react-radio-buttons/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-radio-buttons/index' {
  declare module.exports: $Exports<'react-radio-buttons'>;
}
declare module 'react-radio-buttons/index.jsx' {
  declare module.exports: $Exports<'react-radio-buttons'>;
}
declare module 'react-radio-buttons/lib/index.js' {
  declare module.exports: $Exports<'react-radio-buttons/lib/index'>;
}
declare module 'react-radio-buttons/webpack.config.js' {
  declare module.exports: $Exports<'react-radio-buttons/webpack.config'>;
}
