// flow-typed signature: 15a6113742fde1c3c05efb20d2640578
// flow-typed version: <<STUB>>/react-bootstrap-table-next_v0.1.14/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bootstrap-table-next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bootstrap-table-next' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-bootstrap-table-next/dist/react-bootstrap-table-next' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/dist/react-bootstrap-table-next.min' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/index' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/body' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/bootstrap-table' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/caption' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/cell' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/const' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/container' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/header-cell' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/header' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/props-resolver/column-resolver' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/props-resolver/index' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/props-resolver/remote-resolver' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/row-event-delegater' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/row-section' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/row-selection/selection-cell' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/row-selection/selection-header-cell' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/row-selection/wrapper' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/row' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/sort/caret' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/sort/symbol' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/sort/wrapper' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/store/index' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/store/rows' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/store/selection' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/store/sort' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table-next/lib/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-bootstrap-table-next/dist/react-bootstrap-table-next.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/dist/react-bootstrap-table-next'>;
}
declare module 'react-bootstrap-table-next/dist/react-bootstrap-table-next.min.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/dist/react-bootstrap-table-next.min'>;
}
declare module 'react-bootstrap-table-next/lib/index.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/index'>;
}
declare module 'react-bootstrap-table-next/lib/src/body.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/body'>;
}
declare module 'react-bootstrap-table-next/lib/src/bootstrap-table.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/bootstrap-table'>;
}
declare module 'react-bootstrap-table-next/lib/src/caption.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/caption'>;
}
declare module 'react-bootstrap-table-next/lib/src/cell.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/cell'>;
}
declare module 'react-bootstrap-table-next/lib/src/const.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/const'>;
}
declare module 'react-bootstrap-table-next/lib/src/container.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/container'>;
}
declare module 'react-bootstrap-table-next/lib/src/header-cell.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/header-cell'>;
}
declare module 'react-bootstrap-table-next/lib/src/header.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/header'>;
}
declare module 'react-bootstrap-table-next/lib/src/props-resolver/column-resolver.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/props-resolver/column-resolver'>;
}
declare module 'react-bootstrap-table-next/lib/src/props-resolver/index.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/props-resolver/index'>;
}
declare module 'react-bootstrap-table-next/lib/src/props-resolver/remote-resolver.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/props-resolver/remote-resolver'>;
}
declare module 'react-bootstrap-table-next/lib/src/row-event-delegater.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/row-event-delegater'>;
}
declare module 'react-bootstrap-table-next/lib/src/row-section.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/row-section'>;
}
declare module 'react-bootstrap-table-next/lib/src/row-selection/selection-cell.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/row-selection/selection-cell'>;
}
declare module 'react-bootstrap-table-next/lib/src/row-selection/selection-header-cell.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/row-selection/selection-header-cell'>;
}
declare module 'react-bootstrap-table-next/lib/src/row-selection/wrapper.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/row-selection/wrapper'>;
}
declare module 'react-bootstrap-table-next/lib/src/row.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/row'>;
}
declare module 'react-bootstrap-table-next/lib/src/sort/caret.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/sort/caret'>;
}
declare module 'react-bootstrap-table-next/lib/src/sort/symbol.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/sort/symbol'>;
}
declare module 'react-bootstrap-table-next/lib/src/sort/wrapper.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/sort/wrapper'>;
}
declare module 'react-bootstrap-table-next/lib/src/store/index.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/store/index'>;
}
declare module 'react-bootstrap-table-next/lib/src/store/rows.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/store/rows'>;
}
declare module 'react-bootstrap-table-next/lib/src/store/selection.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/store/selection'>;
}
declare module 'react-bootstrap-table-next/lib/src/store/sort.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/store/sort'>;
}
declare module 'react-bootstrap-table-next/lib/src/utils.js' {
  declare module.exports: $Exports<'react-bootstrap-table-next/lib/src/utils'>;
}
