// flow-typed signature: 594a64a684a12c83dcc9803b96b4c109
// flow-typed version: <<STUB>>/react-leaflet-universal_v^1.1.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-leaflet-universal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-leaflet-universal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-leaflet-universal/dist/decorator' {
  declare module.exports: any;
}

declare module 'react-leaflet-universal/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-leaflet-universal/dist/decorator.js' {
  declare module.exports: $Exports<'react-leaflet-universal/dist/decorator'>;
}
declare module 'react-leaflet-universal/dist/index.js' {
  declare module.exports: $Exports<'react-leaflet-universal/dist/index'>;
}
