// flow-typed signature: ab7fda1884804b68b5043cd34dc5cfc5
// flow-typed version: <<STUB>>/react-intl_v1.2.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-intl/dist/locale-data/aa' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/af' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/agq' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ak' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/am' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ar' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/as' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/asa' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ast' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/az' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/bas' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/be' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/bem' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/bez' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/bg' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/bh' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/bm' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/bn' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/bo' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/br' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/brx' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/bs' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ca' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/cgg' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/chr' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ckb' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/cs' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/cy' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/da' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/dav' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/de' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/dje' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/dsb' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/dua' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/dv' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/dyo' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/dz' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ebu' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ee' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/el' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/en' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/eo' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/es' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/et' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/eu' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ewo' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/fa' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ff' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/fi' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/fil' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/fo' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/fr' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/fur' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/fy' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ga' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/gd' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/gl' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/gsw' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/gu' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/guw' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/guz' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/gv' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ha' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/haw' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/he' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/hi' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/hr' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/hsb' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/hu' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/hy' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ia' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/id' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ig' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ii' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/in' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/is' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/it' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/iu' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/iw' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ja' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/jbo' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/jgo' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ji' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/jmc' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/jv' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/jw' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ka' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/kab' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/kaj' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/kam' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/kcg' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/kde' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/kea' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/khq' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ki' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/kk' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/kkj' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/kl' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/kln' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/km' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/kn' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ko' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/kok' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ks' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ksb' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ksf' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ksh' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ku' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/kw' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ky' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/lag' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/lb' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/lg' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/lkt' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ln' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/lo' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/lt' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/lu' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/luo' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/luy' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/lv' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/mas' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/mer' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/mfe' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/mg' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/mgh' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/mgo' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/mk' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ml' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/mn' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/mo' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/mr' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ms' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/mt' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/mua' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/my' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/nah' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/naq' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/nb' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/nd' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ne' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/nl' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/nmg' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/nn' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/nnh' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/no' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/nqo' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/nr' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/nso' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/nus' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ny' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/nyn' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/om' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/or' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/os' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/pa' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/pap' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/pl' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/prg' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ps' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/pt' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/qu' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/rm' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/rn' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ro' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/rof' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ru' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/rw' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/rwk' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/sah' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/saq' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/sbp' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/se' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/seh' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ses' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/sg' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/sh' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/shi' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/si' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/sk' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/sl' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/sma' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/smi' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/smj' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/smn' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/sms' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/sn' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/so' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/sq' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/sr' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ss' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ssy' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/st' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/sv' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/sw' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/swc' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/syr' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ta' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/te' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/teo' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/th' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ti' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/tig' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/tk' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/tl' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/tn' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/to' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/tr' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ts' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/twq' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/tzm' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ug' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/uk' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ur' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/uz' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/vai' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/ve' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/vi' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/vo' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/vun' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/wa' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/wae' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/wo' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/xh' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/xog' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/yav' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/yi' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/yo' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/zgh' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/zh' {
  declare module.exports: any;
}

declare module 'react-intl/dist/locale-data/zu' {
  declare module.exports: any;
}

declare module 'react-intl/dist/react-intl-with-locales' {
  declare module.exports: any;
}

declare module 'react-intl/dist/react-intl-with-locales.min' {
  declare module.exports: any;
}

declare module 'react-intl/dist/react-intl' {
  declare module.exports: any;
}

declare module 'react-intl/dist/react-intl.min' {
  declare module.exports: any;
}

declare module 'react-intl/lib/components/date' {
  declare module.exports: any;
}

declare module 'react-intl/lib/components/html-message' {
  declare module.exports: any;
}

declare module 'react-intl/lib/components/message' {
  declare module.exports: any;
}

declare module 'react-intl/lib/components/number' {
  declare module.exports: any;
}

declare module 'react-intl/lib/components/relative' {
  declare module.exports: any;
}

declare module 'react-intl/lib/components/time' {
  declare module.exports: any;
}

declare module 'react-intl/lib/en' {
  declare module.exports: any;
}

declare module 'react-intl/lib/escape' {
  declare module.exports: any;
}

declare module 'react-intl/lib/locales' {
  declare module.exports: any;
}

declare module 'react-intl/lib/main' {
  declare module.exports: any;
}

declare module 'react-intl/lib/mixin' {
  declare module.exports: any;
}

declare module 'react-intl/lib/react-intl' {
  declare module.exports: any;
}

declare module 'react-intl/lib/react' {
  declare module.exports: any;
}

declare module 'react-intl/src/components/date' {
  declare module.exports: any;
}

declare module 'react-intl/src/components/html-message' {
  declare module.exports: any;
}

declare module 'react-intl/src/components/message' {
  declare module.exports: any;
}

declare module 'react-intl/src/components/number' {
  declare module.exports: any;
}

declare module 'react-intl/src/components/relative' {
  declare module.exports: any;
}

declare module 'react-intl/src/components/time' {
  declare module.exports: any;
}

declare module 'react-intl/src/en' {
  declare module.exports: any;
}

declare module 'react-intl/src/escape' {
  declare module.exports: any;
}

declare module 'react-intl/src/main' {
  declare module.exports: any;
}

declare module 'react-intl/src/mixin' {
  declare module.exports: any;
}

declare module 'react-intl/src/react-intl' {
  declare module.exports: any;
}

declare module 'react-intl/src/react' {
  declare module.exports: any;
}

declare module 'react-intl/tests/browserify/app' {
  declare module.exports: any;
}

declare module 'react-intl/tests/smoke/smoke' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-intl/dist/locale-data/aa.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/aa'>;
}
declare module 'react-intl/dist/locale-data/af.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/af'>;
}
declare module 'react-intl/dist/locale-data/agq.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/agq'>;
}
declare module 'react-intl/dist/locale-data/ak.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ak'>;
}
declare module 'react-intl/dist/locale-data/am.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/am'>;
}
declare module 'react-intl/dist/locale-data/ar.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ar'>;
}
declare module 'react-intl/dist/locale-data/as.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/as'>;
}
declare module 'react-intl/dist/locale-data/asa.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/asa'>;
}
declare module 'react-intl/dist/locale-data/ast.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ast'>;
}
declare module 'react-intl/dist/locale-data/az.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/az'>;
}
declare module 'react-intl/dist/locale-data/bas.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/bas'>;
}
declare module 'react-intl/dist/locale-data/be.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/be'>;
}
declare module 'react-intl/dist/locale-data/bem.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/bem'>;
}
declare module 'react-intl/dist/locale-data/bez.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/bez'>;
}
declare module 'react-intl/dist/locale-data/bg.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/bg'>;
}
declare module 'react-intl/dist/locale-data/bh.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/bh'>;
}
declare module 'react-intl/dist/locale-data/bm.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/bm'>;
}
declare module 'react-intl/dist/locale-data/bn.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/bn'>;
}
declare module 'react-intl/dist/locale-data/bo.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/bo'>;
}
declare module 'react-intl/dist/locale-data/br.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/br'>;
}
declare module 'react-intl/dist/locale-data/brx.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/brx'>;
}
declare module 'react-intl/dist/locale-data/bs.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/bs'>;
}
declare module 'react-intl/dist/locale-data/ca.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ca'>;
}
declare module 'react-intl/dist/locale-data/cgg.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/cgg'>;
}
declare module 'react-intl/dist/locale-data/chr.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/chr'>;
}
declare module 'react-intl/dist/locale-data/ckb.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ckb'>;
}
declare module 'react-intl/dist/locale-data/cs.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/cs'>;
}
declare module 'react-intl/dist/locale-data/cy.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/cy'>;
}
declare module 'react-intl/dist/locale-data/da.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/da'>;
}
declare module 'react-intl/dist/locale-data/dav.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/dav'>;
}
declare module 'react-intl/dist/locale-data/de.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/de'>;
}
declare module 'react-intl/dist/locale-data/dje.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/dje'>;
}
declare module 'react-intl/dist/locale-data/dsb.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/dsb'>;
}
declare module 'react-intl/dist/locale-data/dua.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/dua'>;
}
declare module 'react-intl/dist/locale-data/dv.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/dv'>;
}
declare module 'react-intl/dist/locale-data/dyo.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/dyo'>;
}
declare module 'react-intl/dist/locale-data/dz.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/dz'>;
}
declare module 'react-intl/dist/locale-data/ebu.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ebu'>;
}
declare module 'react-intl/dist/locale-data/ee.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ee'>;
}
declare module 'react-intl/dist/locale-data/el.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/el'>;
}
declare module 'react-intl/dist/locale-data/en.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/en'>;
}
declare module 'react-intl/dist/locale-data/eo.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/eo'>;
}
declare module 'react-intl/dist/locale-data/es.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/es'>;
}
declare module 'react-intl/dist/locale-data/et.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/et'>;
}
declare module 'react-intl/dist/locale-data/eu.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/eu'>;
}
declare module 'react-intl/dist/locale-data/ewo.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ewo'>;
}
declare module 'react-intl/dist/locale-data/fa.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/fa'>;
}
declare module 'react-intl/dist/locale-data/ff.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ff'>;
}
declare module 'react-intl/dist/locale-data/fi.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/fi'>;
}
declare module 'react-intl/dist/locale-data/fil.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/fil'>;
}
declare module 'react-intl/dist/locale-data/fo.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/fo'>;
}
declare module 'react-intl/dist/locale-data/fr.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/fr'>;
}
declare module 'react-intl/dist/locale-data/fur.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/fur'>;
}
declare module 'react-intl/dist/locale-data/fy.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/fy'>;
}
declare module 'react-intl/dist/locale-data/ga.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ga'>;
}
declare module 'react-intl/dist/locale-data/gd.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/gd'>;
}
declare module 'react-intl/dist/locale-data/gl.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/gl'>;
}
declare module 'react-intl/dist/locale-data/gsw.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/gsw'>;
}
declare module 'react-intl/dist/locale-data/gu.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/gu'>;
}
declare module 'react-intl/dist/locale-data/guw.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/guw'>;
}
declare module 'react-intl/dist/locale-data/guz.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/guz'>;
}
declare module 'react-intl/dist/locale-data/gv.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/gv'>;
}
declare module 'react-intl/dist/locale-data/ha.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ha'>;
}
declare module 'react-intl/dist/locale-data/haw.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/haw'>;
}
declare module 'react-intl/dist/locale-data/he.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/he'>;
}
declare module 'react-intl/dist/locale-data/hi.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/hi'>;
}
declare module 'react-intl/dist/locale-data/hr.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/hr'>;
}
declare module 'react-intl/dist/locale-data/hsb.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/hsb'>;
}
declare module 'react-intl/dist/locale-data/hu.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/hu'>;
}
declare module 'react-intl/dist/locale-data/hy.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/hy'>;
}
declare module 'react-intl/dist/locale-data/ia.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ia'>;
}
declare module 'react-intl/dist/locale-data/id.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/id'>;
}
declare module 'react-intl/dist/locale-data/ig.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ig'>;
}
declare module 'react-intl/dist/locale-data/ii.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ii'>;
}
declare module 'react-intl/dist/locale-data/in.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/in'>;
}
declare module 'react-intl/dist/locale-data/is.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/is'>;
}
declare module 'react-intl/dist/locale-data/it.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/it'>;
}
declare module 'react-intl/dist/locale-data/iu.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/iu'>;
}
declare module 'react-intl/dist/locale-data/iw.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/iw'>;
}
declare module 'react-intl/dist/locale-data/ja.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ja'>;
}
declare module 'react-intl/dist/locale-data/jbo.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/jbo'>;
}
declare module 'react-intl/dist/locale-data/jgo.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/jgo'>;
}
declare module 'react-intl/dist/locale-data/ji.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ji'>;
}
declare module 'react-intl/dist/locale-data/jmc.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/jmc'>;
}
declare module 'react-intl/dist/locale-data/jv.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/jv'>;
}
declare module 'react-intl/dist/locale-data/jw.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/jw'>;
}
declare module 'react-intl/dist/locale-data/ka.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ka'>;
}
declare module 'react-intl/dist/locale-data/kab.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/kab'>;
}
declare module 'react-intl/dist/locale-data/kaj.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/kaj'>;
}
declare module 'react-intl/dist/locale-data/kam.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/kam'>;
}
declare module 'react-intl/dist/locale-data/kcg.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/kcg'>;
}
declare module 'react-intl/dist/locale-data/kde.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/kde'>;
}
declare module 'react-intl/dist/locale-data/kea.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/kea'>;
}
declare module 'react-intl/dist/locale-data/khq.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/khq'>;
}
declare module 'react-intl/dist/locale-data/ki.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ki'>;
}
declare module 'react-intl/dist/locale-data/kk.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/kk'>;
}
declare module 'react-intl/dist/locale-data/kkj.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/kkj'>;
}
declare module 'react-intl/dist/locale-data/kl.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/kl'>;
}
declare module 'react-intl/dist/locale-data/kln.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/kln'>;
}
declare module 'react-intl/dist/locale-data/km.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/km'>;
}
declare module 'react-intl/dist/locale-data/kn.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/kn'>;
}
declare module 'react-intl/dist/locale-data/ko.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ko'>;
}
declare module 'react-intl/dist/locale-data/kok.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/kok'>;
}
declare module 'react-intl/dist/locale-data/ks.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ks'>;
}
declare module 'react-intl/dist/locale-data/ksb.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ksb'>;
}
declare module 'react-intl/dist/locale-data/ksf.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ksf'>;
}
declare module 'react-intl/dist/locale-data/ksh.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ksh'>;
}
declare module 'react-intl/dist/locale-data/ku.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ku'>;
}
declare module 'react-intl/dist/locale-data/kw.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/kw'>;
}
declare module 'react-intl/dist/locale-data/ky.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ky'>;
}
declare module 'react-intl/dist/locale-data/lag.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/lag'>;
}
declare module 'react-intl/dist/locale-data/lb.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/lb'>;
}
declare module 'react-intl/dist/locale-data/lg.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/lg'>;
}
declare module 'react-intl/dist/locale-data/lkt.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/lkt'>;
}
declare module 'react-intl/dist/locale-data/ln.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ln'>;
}
declare module 'react-intl/dist/locale-data/lo.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/lo'>;
}
declare module 'react-intl/dist/locale-data/lt.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/lt'>;
}
declare module 'react-intl/dist/locale-data/lu.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/lu'>;
}
declare module 'react-intl/dist/locale-data/luo.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/luo'>;
}
declare module 'react-intl/dist/locale-data/luy.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/luy'>;
}
declare module 'react-intl/dist/locale-data/lv.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/lv'>;
}
declare module 'react-intl/dist/locale-data/mas.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/mas'>;
}
declare module 'react-intl/dist/locale-data/mer.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/mer'>;
}
declare module 'react-intl/dist/locale-data/mfe.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/mfe'>;
}
declare module 'react-intl/dist/locale-data/mg.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/mg'>;
}
declare module 'react-intl/dist/locale-data/mgh.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/mgh'>;
}
declare module 'react-intl/dist/locale-data/mgo.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/mgo'>;
}
declare module 'react-intl/dist/locale-data/mk.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/mk'>;
}
declare module 'react-intl/dist/locale-data/ml.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ml'>;
}
declare module 'react-intl/dist/locale-data/mn.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/mn'>;
}
declare module 'react-intl/dist/locale-data/mo.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/mo'>;
}
declare module 'react-intl/dist/locale-data/mr.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/mr'>;
}
declare module 'react-intl/dist/locale-data/ms.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ms'>;
}
declare module 'react-intl/dist/locale-data/mt.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/mt'>;
}
declare module 'react-intl/dist/locale-data/mua.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/mua'>;
}
declare module 'react-intl/dist/locale-data/my.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/my'>;
}
declare module 'react-intl/dist/locale-data/nah.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/nah'>;
}
declare module 'react-intl/dist/locale-data/naq.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/naq'>;
}
declare module 'react-intl/dist/locale-data/nb.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/nb'>;
}
declare module 'react-intl/dist/locale-data/nd.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/nd'>;
}
declare module 'react-intl/dist/locale-data/ne.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ne'>;
}
declare module 'react-intl/dist/locale-data/nl.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/nl'>;
}
declare module 'react-intl/dist/locale-data/nmg.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/nmg'>;
}
declare module 'react-intl/dist/locale-data/nn.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/nn'>;
}
declare module 'react-intl/dist/locale-data/nnh.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/nnh'>;
}
declare module 'react-intl/dist/locale-data/no.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/no'>;
}
declare module 'react-intl/dist/locale-data/nqo.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/nqo'>;
}
declare module 'react-intl/dist/locale-data/nr.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/nr'>;
}
declare module 'react-intl/dist/locale-data/nso.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/nso'>;
}
declare module 'react-intl/dist/locale-data/nus.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/nus'>;
}
declare module 'react-intl/dist/locale-data/ny.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ny'>;
}
declare module 'react-intl/dist/locale-data/nyn.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/nyn'>;
}
declare module 'react-intl/dist/locale-data/om.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/om'>;
}
declare module 'react-intl/dist/locale-data/or.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/or'>;
}
declare module 'react-intl/dist/locale-data/os.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/os'>;
}
declare module 'react-intl/dist/locale-data/pa.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/pa'>;
}
declare module 'react-intl/dist/locale-data/pap.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/pap'>;
}
declare module 'react-intl/dist/locale-data/pl.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/pl'>;
}
declare module 'react-intl/dist/locale-data/prg.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/prg'>;
}
declare module 'react-intl/dist/locale-data/ps.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ps'>;
}
declare module 'react-intl/dist/locale-data/pt.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/pt'>;
}
declare module 'react-intl/dist/locale-data/qu.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/qu'>;
}
declare module 'react-intl/dist/locale-data/rm.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/rm'>;
}
declare module 'react-intl/dist/locale-data/rn.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/rn'>;
}
declare module 'react-intl/dist/locale-data/ro.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ro'>;
}
declare module 'react-intl/dist/locale-data/rof.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/rof'>;
}
declare module 'react-intl/dist/locale-data/ru.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ru'>;
}
declare module 'react-intl/dist/locale-data/rw.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/rw'>;
}
declare module 'react-intl/dist/locale-data/rwk.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/rwk'>;
}
declare module 'react-intl/dist/locale-data/sah.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/sah'>;
}
declare module 'react-intl/dist/locale-data/saq.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/saq'>;
}
declare module 'react-intl/dist/locale-data/sbp.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/sbp'>;
}
declare module 'react-intl/dist/locale-data/se.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/se'>;
}
declare module 'react-intl/dist/locale-data/seh.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/seh'>;
}
declare module 'react-intl/dist/locale-data/ses.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ses'>;
}
declare module 'react-intl/dist/locale-data/sg.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/sg'>;
}
declare module 'react-intl/dist/locale-data/sh.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/sh'>;
}
declare module 'react-intl/dist/locale-data/shi.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/shi'>;
}
declare module 'react-intl/dist/locale-data/si.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/si'>;
}
declare module 'react-intl/dist/locale-data/sk.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/sk'>;
}
declare module 'react-intl/dist/locale-data/sl.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/sl'>;
}
declare module 'react-intl/dist/locale-data/sma.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/sma'>;
}
declare module 'react-intl/dist/locale-data/smi.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/smi'>;
}
declare module 'react-intl/dist/locale-data/smj.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/smj'>;
}
declare module 'react-intl/dist/locale-data/smn.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/smn'>;
}
declare module 'react-intl/dist/locale-data/sms.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/sms'>;
}
declare module 'react-intl/dist/locale-data/sn.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/sn'>;
}
declare module 'react-intl/dist/locale-data/so.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/so'>;
}
declare module 'react-intl/dist/locale-data/sq.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/sq'>;
}
declare module 'react-intl/dist/locale-data/sr.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/sr'>;
}
declare module 'react-intl/dist/locale-data/ss.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ss'>;
}
declare module 'react-intl/dist/locale-data/ssy.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ssy'>;
}
declare module 'react-intl/dist/locale-data/st.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/st'>;
}
declare module 'react-intl/dist/locale-data/sv.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/sv'>;
}
declare module 'react-intl/dist/locale-data/sw.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/sw'>;
}
declare module 'react-intl/dist/locale-data/swc.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/swc'>;
}
declare module 'react-intl/dist/locale-data/syr.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/syr'>;
}
declare module 'react-intl/dist/locale-data/ta.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ta'>;
}
declare module 'react-intl/dist/locale-data/te.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/te'>;
}
declare module 'react-intl/dist/locale-data/teo.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/teo'>;
}
declare module 'react-intl/dist/locale-data/th.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/th'>;
}
declare module 'react-intl/dist/locale-data/ti.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ti'>;
}
declare module 'react-intl/dist/locale-data/tig.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/tig'>;
}
declare module 'react-intl/dist/locale-data/tk.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/tk'>;
}
declare module 'react-intl/dist/locale-data/tl.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/tl'>;
}
declare module 'react-intl/dist/locale-data/tn.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/tn'>;
}
declare module 'react-intl/dist/locale-data/to.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/to'>;
}
declare module 'react-intl/dist/locale-data/tr.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/tr'>;
}
declare module 'react-intl/dist/locale-data/ts.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ts'>;
}
declare module 'react-intl/dist/locale-data/twq.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/twq'>;
}
declare module 'react-intl/dist/locale-data/tzm.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/tzm'>;
}
declare module 'react-intl/dist/locale-data/ug.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ug'>;
}
declare module 'react-intl/dist/locale-data/uk.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/uk'>;
}
declare module 'react-intl/dist/locale-data/ur.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ur'>;
}
declare module 'react-intl/dist/locale-data/uz.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/uz'>;
}
declare module 'react-intl/dist/locale-data/vai.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/vai'>;
}
declare module 'react-intl/dist/locale-data/ve.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/ve'>;
}
declare module 'react-intl/dist/locale-data/vi.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/vi'>;
}
declare module 'react-intl/dist/locale-data/vo.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/vo'>;
}
declare module 'react-intl/dist/locale-data/vun.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/vun'>;
}
declare module 'react-intl/dist/locale-data/wa.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/wa'>;
}
declare module 'react-intl/dist/locale-data/wae.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/wae'>;
}
declare module 'react-intl/dist/locale-data/wo.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/wo'>;
}
declare module 'react-intl/dist/locale-data/xh.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/xh'>;
}
declare module 'react-intl/dist/locale-data/xog.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/xog'>;
}
declare module 'react-intl/dist/locale-data/yav.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/yav'>;
}
declare module 'react-intl/dist/locale-data/yi.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/yi'>;
}
declare module 'react-intl/dist/locale-data/yo.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/yo'>;
}
declare module 'react-intl/dist/locale-data/zgh.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/zgh'>;
}
declare module 'react-intl/dist/locale-data/zh.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/zh'>;
}
declare module 'react-intl/dist/locale-data/zu.js' {
  declare module.exports: $Exports<'react-intl/dist/locale-data/zu'>;
}
declare module 'react-intl/dist/react-intl-with-locales.js' {
  declare module.exports: $Exports<'react-intl/dist/react-intl-with-locales'>;
}
declare module 'react-intl/dist/react-intl-with-locales.min.js' {
  declare module.exports: $Exports<'react-intl/dist/react-intl-with-locales.min'>;
}
declare module 'react-intl/dist/react-intl.js' {
  declare module.exports: $Exports<'react-intl/dist/react-intl'>;
}
declare module 'react-intl/dist/react-intl.min.js' {
  declare module.exports: $Exports<'react-intl/dist/react-intl.min'>;
}
declare module 'react-intl/index' {
  declare module.exports: $Exports<'react-intl'>;
}
declare module 'react-intl/index.js' {
  declare module.exports: $Exports<'react-intl'>;
}
declare module 'react-intl/lib/components/date.js' {
  declare module.exports: $Exports<'react-intl/lib/components/date'>;
}
declare module 'react-intl/lib/components/html-message.js' {
  declare module.exports: $Exports<'react-intl/lib/components/html-message'>;
}
declare module 'react-intl/lib/components/message.js' {
  declare module.exports: $Exports<'react-intl/lib/components/message'>;
}
declare module 'react-intl/lib/components/number.js' {
  declare module.exports: $Exports<'react-intl/lib/components/number'>;
}
declare module 'react-intl/lib/components/relative.js' {
  declare module.exports: $Exports<'react-intl/lib/components/relative'>;
}
declare module 'react-intl/lib/components/time.js' {
  declare module.exports: $Exports<'react-intl/lib/components/time'>;
}
declare module 'react-intl/lib/en.js' {
  declare module.exports: $Exports<'react-intl/lib/en'>;
}
declare module 'react-intl/lib/escape.js' {
  declare module.exports: $Exports<'react-intl/lib/escape'>;
}
declare module 'react-intl/lib/locales.js' {
  declare module.exports: $Exports<'react-intl/lib/locales'>;
}
declare module 'react-intl/lib/main.js' {
  declare module.exports: $Exports<'react-intl/lib/main'>;
}
declare module 'react-intl/lib/mixin.js' {
  declare module.exports: $Exports<'react-intl/lib/mixin'>;
}
declare module 'react-intl/lib/react-intl.js' {
  declare module.exports: $Exports<'react-intl/lib/react-intl'>;
}
declare module 'react-intl/lib/react.js' {
  declare module.exports: $Exports<'react-intl/lib/react'>;
}
declare module 'react-intl/src/components/date.js' {
  declare module.exports: $Exports<'react-intl/src/components/date'>;
}
declare module 'react-intl/src/components/html-message.js' {
  declare module.exports: $Exports<'react-intl/src/components/html-message'>;
}
declare module 'react-intl/src/components/message.js' {
  declare module.exports: $Exports<'react-intl/src/components/message'>;
}
declare module 'react-intl/src/components/number.js' {
  declare module.exports: $Exports<'react-intl/src/components/number'>;
}
declare module 'react-intl/src/components/relative.js' {
  declare module.exports: $Exports<'react-intl/src/components/relative'>;
}
declare module 'react-intl/src/components/time.js' {
  declare module.exports: $Exports<'react-intl/src/components/time'>;
}
declare module 'react-intl/src/en.js' {
  declare module.exports: $Exports<'react-intl/src/en'>;
}
declare module 'react-intl/src/escape.js' {
  declare module.exports: $Exports<'react-intl/src/escape'>;
}
declare module 'react-intl/src/main.js' {
  declare module.exports: $Exports<'react-intl/src/main'>;
}
declare module 'react-intl/src/mixin.js' {
  declare module.exports: $Exports<'react-intl/src/mixin'>;
}
declare module 'react-intl/src/react-intl.js' {
  declare module.exports: $Exports<'react-intl/src/react-intl'>;
}
declare module 'react-intl/src/react.js' {
  declare module.exports: $Exports<'react-intl/src/react'>;
}
declare module 'react-intl/tests/browserify/app.js' {
  declare module.exports: $Exports<'react-intl/tests/browserify/app'>;
}
declare module 'react-intl/tests/smoke/smoke.js' {
  declare module.exports: $Exports<'react-intl/tests/smoke/smoke'>;
}
