// flow-typed signature: 026d3ce853f9afcf395d1fab33a1baa5
// flow-typed version: <<STUB>>/react-truncate_v^2.0.5/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-truncate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-truncate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-truncate/lib/Truncate.CommonJS' {
  declare module.exports: any;
}

declare module 'react-truncate/lib/Truncate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-truncate/lib/Truncate.CommonJS.js' {
  declare module.exports: $Exports<'react-truncate/lib/Truncate.CommonJS'>;
}
declare module 'react-truncate/lib/Truncate.js' {
  declare module.exports: $Exports<'react-truncate/lib/Truncate'>;
}
