// flow-typed signature: a74606d7d6bf6503ccb09d8db84a3f93
// flow-typed version: <<STUB>>/react-dropdown-date_v0.0.13/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dropdown-date'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dropdown-date' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dropdown-date/build/index' {
  declare module.exports: any;
}

declare module 'react-dropdown-date/src/date' {
  declare module.exports: any;
}

declare module 'react-dropdown-date/src/helper' {
  declare module.exports: any;
}

declare module 'react-dropdown-date/src/index' {
  declare module.exports: any;
}

declare module 'react-dropdown-date/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dropdown-date/build/index.js' {
  declare module.exports: $Exports<'react-dropdown-date/build/index'>;
}
declare module 'react-dropdown-date/src/date.js' {
  declare module.exports: $Exports<'react-dropdown-date/src/date'>;
}
declare module 'react-dropdown-date/src/helper.js' {
  declare module.exports: $Exports<'react-dropdown-date/src/helper'>;
}
declare module 'react-dropdown-date/src/index.js' {
  declare module.exports: $Exports<'react-dropdown-date/src/index'>;
}
declare module 'react-dropdown-date/webpack.config.js' {
  declare module.exports: $Exports<'react-dropdown-date/webpack.config'>;
}
