// flow-typed signature: f3861f0287635045bc57de83c86ef2ab
// flow-typed version: <<STUB>>/react-checkbox-group_vhttps://github.com/cap-collectif/react-checkbox-group/tarball/296721a62a682c5e441bdd449704550b69257af9/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-checkbox-group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-checkbox-group' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-checkbox-group/react-checkbox-group' {
  declare module.exports: any;
}

declare module 'react-checkbox-group/react-checkbox-group' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-checkbox-group/react-checkbox-group.js' {
  declare module.exports: $Exports<'react-checkbox-group/react-checkbox-group'>;
}
declare module 'react-checkbox-group/react-checkbox-group.jsx' {
  declare module.exports: $Exports<'react-checkbox-group/react-checkbox-group'>;
}
