// flow-typed signature: 063bec90c4d234f430718000f8801019
// flow-typed version: <<STUB>>/react-nl2br_v^0.2.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-nl2br'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-nl2br' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-nl2br/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-nl2br/index' {
  declare module.exports: $Exports<'react-nl2br'>;
}
declare module 'react-nl2br/index.js' {
  declare module.exports: $Exports<'react-nl2br'>;
}
declare module 'react-nl2br/test.js' {
  declare module.exports: $Exports<'react-nl2br/test'>;
}
