// flow-typed signature: af1e46be10dece7427d8857ec9da91ce
// flow-typed version: <<STUB>>/react-places-autocomplete_v^5.3.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-places-autocomplete'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-places-autocomplete' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-places-autocomplete/dist/defaultStyles' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/index' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/index.umd' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/index.umd.min' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/PlacesAutocomplete' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/tests/testHelper' {
  declare module.exports: any;
}

declare module 'react-places-autocomplete/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-places-autocomplete/dist/defaultStyles.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/defaultStyles'>;
}
declare module 'react-places-autocomplete/dist/index.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/index'>;
}
declare module 'react-places-autocomplete/dist/index.umd.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/index.umd'>;
}
declare module 'react-places-autocomplete/dist/index.umd.min.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/index.umd.min'>;
}
declare module 'react-places-autocomplete/dist/PlacesAutocomplete.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/PlacesAutocomplete'>;
}
declare module 'react-places-autocomplete/dist/tests/testHelper.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/tests/testHelper'>;
}
declare module 'react-places-autocomplete/dist/utils.js' {
  declare module.exports: $Exports<'react-places-autocomplete/dist/utils'>;
}
