// flow-typed signature: 7f9dbd2bc66b2096d3d010e8e3956b92
// flow-typed version: <<STUB>>/react-truncate_v^2.0.3/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-truncate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-truncate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-truncate/lib/Truncate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-truncate/lib/Truncate.js' {
  declare module.exports: $Exports<'react-truncate/lib/Truncate'>;
}
