// flow-typed signature: 6af1a939dc125acab9b678179fa37ae1
// flow-typed version: <<STUB>>/react-radio_v^2.1.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-radio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-radio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-radio/lib/index' {
  declare module.exports: any;
}

declare module 'react-radio/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-radio/index' {
  declare module.exports: $Exports<'react-radio'>;
}
declare module 'react-radio/index.js' {
  declare module.exports: $Exports<'react-radio'>;
}
declare module 'react-radio/lib/index.js' {
  declare module.exports: $Exports<'react-radio/lib/index'>;
}
declare module 'react-radio/src/index.js' {
  declare module.exports: $Exports<'react-radio/src/index'>;
}
