// flow-typed signature: 3ee04ff4fc71e9f2fed8c3b04144c880
// flow-typed version: <<STUB>>/readmore_v0.0.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'readmore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'readmore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'readmore/lib/readmore' {
  declare module.exports: any;
}

// Filename aliases
declare module 'readmore/lib/readmore.js' {
  declare module.exports: $Exports<'readmore/lib/readmore'>;
}
