// flow-typed signature: 5fc2de53e89e4d9e4c6f6399eb21b8a9
// flow-typed version: <<STUB>>/sass-brunch_v^2.10.4/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-brunch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-brunch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'sass-brunch/index' {
  declare module.exports: $Exports<'sass-brunch'>;
}
declare module 'sass-brunch/index.js' {
  declare module.exports: $Exports<'sass-brunch'>;
}
