// flow-typed signature: 8582947d41fcdb0a225abf7fd0ca7d1c
// flow-typed version: <<STUB>>/sass-brunch_vhttps://github.com/gavinkflam/sass-brunch/tarball/cbf2edf2646ded550c7f333cc921f295773b1d4e/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-brunch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-brunch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sass-brunch/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sass-brunch/index' {
  declare module.exports: $Exports<'sass-brunch'>;
}
declare module 'sass-brunch/index.js' {
  declare module.exports: $Exports<'sass-brunch'>;
}
declare module 'sass-brunch/test.js' {
  declare module.exports: $Exports<'sass-brunch/test'>;
}
