// flow-typed signature: bbc447a9e352af2bef924bd19c5317de
// flow-typed version: <<STUB>>/stickyfilljs_v2.1.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stickyfilljs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stickyfilljs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stickyfilljs/dist/stickyfill.es6' {
  declare module.exports: any;
}

declare module 'stickyfilljs/dist/stickyfill' {
  declare module.exports: any;
}

declare module 'stickyfilljs/dist/stickyfill.min' {
  declare module.exports: any;
}

declare module 'stickyfilljs/Gruntfile' {
  declare module.exports: any;
}

declare module 'stickyfilljs/src/stickyfill' {
  declare module.exports: any;
}

declare module 'stickyfilljs/test/js/jquery-3.1.1.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stickyfilljs/dist/stickyfill.es6.js' {
  declare module.exports: $Exports<'stickyfilljs/dist/stickyfill.es6'>;
}
declare module 'stickyfilljs/dist/stickyfill.js' {
  declare module.exports: $Exports<'stickyfilljs/dist/stickyfill'>;
}
declare module 'stickyfilljs/dist/stickyfill.min.js' {
  declare module.exports: $Exports<'stickyfilljs/dist/stickyfill.min'>;
}
declare module 'stickyfilljs/Gruntfile.js' {
  declare module.exports: $Exports<'stickyfilljs/Gruntfile'>;
}
declare module 'stickyfilljs/src/stickyfill.js' {
  declare module.exports: $Exports<'stickyfilljs/src/stickyfill'>;
}
declare module 'stickyfilljs/test/js/jquery-3.1.1.min.js' {
  declare module.exports: $Exports<'stickyfilljs/test/js/jquery-3.1.1.min'>;
}
