// flow-typed signature: 4de27324493569ebe60b99cdf468a753
// flow-typed version: <<STUB>>/styled-spinkit_v0.2.1/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-spinkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-spinkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-spinkit/dist/styled-spinkit.es' {
  declare module.exports: any;
}

declare module 'styled-spinkit/flow-typed/enzyme-to-json' {
  declare module.exports: any;
}

declare module 'styled-spinkit/flow-typed/npm/enzyme_v3.x.x' {
  declare module.exports: any;
}

declare module 'styled-spinkit/flow-typed/npm/jest_v22.x.x' {
  declare module.exports: any;
}

declare module 'styled-spinkit/flow-typed/npm/styled-components_v2.x.x' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/ChasingDots/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/ChasingDots/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/Circle/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/Circle/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/CubeGrid/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/CubeGrid/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/DoubleDounce/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/DoubleDounce/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/FadingCircle/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/FadingCircle/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/FoldingCube/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/FoldingCube/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/Pulse/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/Pulse/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/RotaingPlane/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/RotaingPlane/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/ThreeBounce/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/ThreeBounce/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/util/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/WanderingCubes/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/WanderingCubes/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/WaveLoading/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/lib/WaveLoading/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/ChasingDots/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/ChasingDots/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/ChasingDots/tests/index.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/ChasingDots/tests/styles.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/Circle/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/Circle/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/Circle/tests/index.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/Circle/tests/styles.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/CubeGrid/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/CubeGrid/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/CubeGrid/tests/index.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/CubeGrid/tests/styles.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/DoubleDounce/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/DoubleDounce/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/DoubleDounce/tests/index.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/DoubleDounce/tests/styles.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/FadingCircle/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/FadingCircle/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/FadingCircle/tests/index.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/FadingCircle/tests/styles.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/FoldingCube/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/FoldingCube/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/FoldingCube/tests/index.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/FoldingCube/tests/styles.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/Pulse/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/Pulse/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/Pulse/tests/index.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/Pulse/tests/styles.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/RotaingPlane/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/RotaingPlane/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/RotaingPlane/tests/index.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/RotaingPlane/tests/styles.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/ThreeBounce/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/ThreeBounce/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/ThreeBounce/tests/index.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/ThreeBounce/tests/styles.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/util/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/WanderingCubes/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/WanderingCubes/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/WanderingCubes/tests/index.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/WanderingCubes/tests/styles.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/WaveLoading/index' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/WaveLoading/styles' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/WaveLoading/tests/index.test' {
  declare module.exports: any;
}

declare module 'styled-spinkit/src/WaveLoading/tests/styles.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-spinkit/dist/styled-spinkit.es.js' {
  declare module.exports: $Exports<'styled-spinkit/dist/styled-spinkit.es'>;
}
declare module 'styled-spinkit/flow-typed/enzyme-to-json.js' {
  declare module.exports: $Exports<'styled-spinkit/flow-typed/enzyme-to-json'>;
}
declare module 'styled-spinkit/flow-typed/npm/enzyme_v3.x.x.js' {
  declare module.exports: $Exports<'styled-spinkit/flow-typed/npm/enzyme_v3.x.x'>;
}
declare module 'styled-spinkit/flow-typed/npm/jest_v22.x.x.js' {
  declare module.exports: $Exports<'styled-spinkit/flow-typed/npm/jest_v22.x.x'>;
}
declare module 'styled-spinkit/flow-typed/npm/styled-components_v2.x.x.js' {
  declare module.exports: $Exports<'styled-spinkit/flow-typed/npm/styled-components_v2.x.x'>;
}
declare module 'styled-spinkit/lib/ChasingDots/index.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/ChasingDots/index'>;
}
declare module 'styled-spinkit/lib/ChasingDots/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/ChasingDots/styles'>;
}
declare module 'styled-spinkit/lib/Circle/index.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/Circle/index'>;
}
declare module 'styled-spinkit/lib/Circle/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/Circle/styles'>;
}
declare module 'styled-spinkit/lib/CubeGrid/index.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/CubeGrid/index'>;
}
declare module 'styled-spinkit/lib/CubeGrid/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/CubeGrid/styles'>;
}
declare module 'styled-spinkit/lib/DoubleDounce/index.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/DoubleDounce/index'>;
}
declare module 'styled-spinkit/lib/DoubleDounce/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/DoubleDounce/styles'>;
}
declare module 'styled-spinkit/lib/FadingCircle/index.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/FadingCircle/index'>;
}
declare module 'styled-spinkit/lib/FadingCircle/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/FadingCircle/styles'>;
}
declare module 'styled-spinkit/lib/FoldingCube/index.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/FoldingCube/index'>;
}
declare module 'styled-spinkit/lib/FoldingCube/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/FoldingCube/styles'>;
}
declare module 'styled-spinkit/lib/index.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/index'>;
}
declare module 'styled-spinkit/lib/Pulse/index.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/Pulse/index'>;
}
declare module 'styled-spinkit/lib/Pulse/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/Pulse/styles'>;
}
declare module 'styled-spinkit/lib/RotaingPlane/index.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/RotaingPlane/index'>;
}
declare module 'styled-spinkit/lib/RotaingPlane/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/RotaingPlane/styles'>;
}
declare module 'styled-spinkit/lib/ThreeBounce/index.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/ThreeBounce/index'>;
}
declare module 'styled-spinkit/lib/ThreeBounce/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/ThreeBounce/styles'>;
}
declare module 'styled-spinkit/lib/util/index.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/util/index'>;
}
declare module 'styled-spinkit/lib/WanderingCubes/index.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/WanderingCubes/index'>;
}
declare module 'styled-spinkit/lib/WanderingCubes/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/WanderingCubes/styles'>;
}
declare module 'styled-spinkit/lib/WaveLoading/index.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/WaveLoading/index'>;
}
declare module 'styled-spinkit/lib/WaveLoading/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/lib/WaveLoading/styles'>;
}
declare module 'styled-spinkit/src/ChasingDots/index.js' {
  declare module.exports: $Exports<'styled-spinkit/src/ChasingDots/index'>;
}
declare module 'styled-spinkit/src/ChasingDots/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/src/ChasingDots/styles'>;
}
declare module 'styled-spinkit/src/ChasingDots/tests/index.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/ChasingDots/tests/index.test'>;
}
declare module 'styled-spinkit/src/ChasingDots/tests/styles.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/ChasingDots/tests/styles.test'>;
}
declare module 'styled-spinkit/src/Circle/index.js' {
  declare module.exports: $Exports<'styled-spinkit/src/Circle/index'>;
}
declare module 'styled-spinkit/src/Circle/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/src/Circle/styles'>;
}
declare module 'styled-spinkit/src/Circle/tests/index.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/Circle/tests/index.test'>;
}
declare module 'styled-spinkit/src/Circle/tests/styles.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/Circle/tests/styles.test'>;
}
declare module 'styled-spinkit/src/CubeGrid/index.js' {
  declare module.exports: $Exports<'styled-spinkit/src/CubeGrid/index'>;
}
declare module 'styled-spinkit/src/CubeGrid/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/src/CubeGrid/styles'>;
}
declare module 'styled-spinkit/src/CubeGrid/tests/index.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/CubeGrid/tests/index.test'>;
}
declare module 'styled-spinkit/src/CubeGrid/tests/styles.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/CubeGrid/tests/styles.test'>;
}
declare module 'styled-spinkit/src/DoubleDounce/index.js' {
  declare module.exports: $Exports<'styled-spinkit/src/DoubleDounce/index'>;
}
declare module 'styled-spinkit/src/DoubleDounce/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/src/DoubleDounce/styles'>;
}
declare module 'styled-spinkit/src/DoubleDounce/tests/index.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/DoubleDounce/tests/index.test'>;
}
declare module 'styled-spinkit/src/DoubleDounce/tests/styles.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/DoubleDounce/tests/styles.test'>;
}
declare module 'styled-spinkit/src/FadingCircle/index.js' {
  declare module.exports: $Exports<'styled-spinkit/src/FadingCircle/index'>;
}
declare module 'styled-spinkit/src/FadingCircle/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/src/FadingCircle/styles'>;
}
declare module 'styled-spinkit/src/FadingCircle/tests/index.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/FadingCircle/tests/index.test'>;
}
declare module 'styled-spinkit/src/FadingCircle/tests/styles.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/FadingCircle/tests/styles.test'>;
}
declare module 'styled-spinkit/src/FoldingCube/index.js' {
  declare module.exports: $Exports<'styled-spinkit/src/FoldingCube/index'>;
}
declare module 'styled-spinkit/src/FoldingCube/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/src/FoldingCube/styles'>;
}
declare module 'styled-spinkit/src/FoldingCube/tests/index.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/FoldingCube/tests/index.test'>;
}
declare module 'styled-spinkit/src/FoldingCube/tests/styles.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/FoldingCube/tests/styles.test'>;
}
declare module 'styled-spinkit/src/index.js' {
  declare module.exports: $Exports<'styled-spinkit/src/index'>;
}
declare module 'styled-spinkit/src/Pulse/index.js' {
  declare module.exports: $Exports<'styled-spinkit/src/Pulse/index'>;
}
declare module 'styled-spinkit/src/Pulse/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/src/Pulse/styles'>;
}
declare module 'styled-spinkit/src/Pulse/tests/index.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/Pulse/tests/index.test'>;
}
declare module 'styled-spinkit/src/Pulse/tests/styles.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/Pulse/tests/styles.test'>;
}
declare module 'styled-spinkit/src/RotaingPlane/index.js' {
  declare module.exports: $Exports<'styled-spinkit/src/RotaingPlane/index'>;
}
declare module 'styled-spinkit/src/RotaingPlane/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/src/RotaingPlane/styles'>;
}
declare module 'styled-spinkit/src/RotaingPlane/tests/index.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/RotaingPlane/tests/index.test'>;
}
declare module 'styled-spinkit/src/RotaingPlane/tests/styles.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/RotaingPlane/tests/styles.test'>;
}
declare module 'styled-spinkit/src/ThreeBounce/index.js' {
  declare module.exports: $Exports<'styled-spinkit/src/ThreeBounce/index'>;
}
declare module 'styled-spinkit/src/ThreeBounce/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/src/ThreeBounce/styles'>;
}
declare module 'styled-spinkit/src/ThreeBounce/tests/index.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/ThreeBounce/tests/index.test'>;
}
declare module 'styled-spinkit/src/ThreeBounce/tests/styles.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/ThreeBounce/tests/styles.test'>;
}
declare module 'styled-spinkit/src/util/index.js' {
  declare module.exports: $Exports<'styled-spinkit/src/util/index'>;
}
declare module 'styled-spinkit/src/WanderingCubes/index.js' {
  declare module.exports: $Exports<'styled-spinkit/src/WanderingCubes/index'>;
}
declare module 'styled-spinkit/src/WanderingCubes/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/src/WanderingCubes/styles'>;
}
declare module 'styled-spinkit/src/WanderingCubes/tests/index.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/WanderingCubes/tests/index.test'>;
}
declare module 'styled-spinkit/src/WanderingCubes/tests/styles.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/WanderingCubes/tests/styles.test'>;
}
declare module 'styled-spinkit/src/WaveLoading/index.js' {
  declare module.exports: $Exports<'styled-spinkit/src/WaveLoading/index'>;
}
declare module 'styled-spinkit/src/WaveLoading/styles.js' {
  declare module.exports: $Exports<'styled-spinkit/src/WaveLoading/styles'>;
}
declare module 'styled-spinkit/src/WaveLoading/tests/index.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/WaveLoading/tests/index.test'>;
}
declare module 'styled-spinkit/src/WaveLoading/tests/styles.test.js' {
  declare module.exports: $Exports<'styled-spinkit/src/WaveLoading/tests/styles.test'>;
}
