// flow-typed signature: 536e00eb83d15b5bc97ec17ef0529704
// flow-typed version: <<STUB>>/uglify-js-brunch_v^2.0.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uglify-js-brunch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'uglify-js-brunch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'uglify-js-brunch/index' {
  declare module.exports: $Exports<'uglify-js-brunch'>;
}
declare module 'uglify-js-brunch/index.js' {
  declare module.exports: $Exports<'uglify-js-brunch'>;
}
