// flow-typed signature: daec78e199038d6c8837d55cf7fc39cb
// flow-typed version: <<STUB>>/uglify-js-brunch_v^2.10.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uglify-js-brunch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uglify-js-brunch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'uglify-js-brunch/index' {
  declare module.exports: $Exports<'uglify-js-brunch'>;
}
declare module 'uglify-js-brunch/index.js' {
  declare module.exports: $Exports<'uglify-js-brunch'>;
}
