// flow-typed signature: 5f537b0cd763502ba62b32c31fc5b15b
// flow-typed version: <<STUB>>/vscode-apollo-relay_v1.4.3/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vscode-apollo-relay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vscode-apollo-relay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vscode-apollo-relay/dist/argumentDefinitions' {
  declare module.exports: any;
}

declare module 'vscode-apollo-relay/dist/dependencies' {
  declare module.exports: any;
}

declare module 'vscode-apollo-relay/dist/generateConfig' {
  declare module.exports: any;
}

declare module 'vscode-apollo-relay/dist/generateDirectivesFile' {
  declare module.exports: any;
}

declare module 'vscode-apollo-relay/dist' {
  declare module.exports: any;
}

declare module 'vscode-apollo-relay/dist/RelayArgumentsOfCorrectType' {
  declare module.exports: any;
}

declare module 'vscode-apollo-relay/dist/RelayCompatRequiredPageInfoFields' {
  declare module.exports: any;
}

declare module 'vscode-apollo-relay/dist/RelayDefaultValueOfCorrectType' {
  declare module.exports: any;
}

declare module 'vscode-apollo-relay/dist/RelayKnownArgumentNames' {
  declare module.exports: any;
}

declare module 'vscode-apollo-relay/dist/RelayKnownVariableNames' {
  declare module.exports: any;
}

declare module 'vscode-apollo-relay/dist/RelayVariablesInAllowedPosition' {
  declare module.exports: any;
}

declare module 'vscode-apollo-relay/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vscode-apollo-relay/dist/argumentDefinitions.js' {
  declare module.exports: $Exports<'vscode-apollo-relay/dist/argumentDefinitions'>;
}
declare module 'vscode-apollo-relay/dist/dependencies.js' {
  declare module.exports: $Exports<'vscode-apollo-relay/dist/dependencies'>;
}
declare module 'vscode-apollo-relay/dist/generateConfig.js' {
  declare module.exports: $Exports<'vscode-apollo-relay/dist/generateConfig'>;
}
declare module 'vscode-apollo-relay/dist/generateDirectivesFile.js' {
  declare module.exports: $Exports<'vscode-apollo-relay/dist/generateDirectivesFile'>;
}
declare module 'vscode-apollo-relay/dist/index' {
  declare module.exports: $Exports<'vscode-apollo-relay/dist'>;
}
declare module 'vscode-apollo-relay/dist/index.js' {
  declare module.exports: $Exports<'vscode-apollo-relay/dist'>;
}
declare module 'vscode-apollo-relay/dist/RelayArgumentsOfCorrectType.js' {
  declare module.exports: $Exports<'vscode-apollo-relay/dist/RelayArgumentsOfCorrectType'>;
}
declare module 'vscode-apollo-relay/dist/RelayCompatRequiredPageInfoFields.js' {
  declare module.exports: $Exports<'vscode-apollo-relay/dist/RelayCompatRequiredPageInfoFields'>;
}
declare module 'vscode-apollo-relay/dist/RelayDefaultValueOfCorrectType.js' {
  declare module.exports: $Exports<'vscode-apollo-relay/dist/RelayDefaultValueOfCorrectType'>;
}
declare module 'vscode-apollo-relay/dist/RelayKnownArgumentNames.js' {
  declare module.exports: $Exports<'vscode-apollo-relay/dist/RelayKnownArgumentNames'>;
}
declare module 'vscode-apollo-relay/dist/RelayKnownVariableNames.js' {
  declare module.exports: $Exports<'vscode-apollo-relay/dist/RelayKnownVariableNames'>;
}
declare module 'vscode-apollo-relay/dist/RelayVariablesInAllowedPosition.js' {
  declare module.exports: $Exports<'vscode-apollo-relay/dist/RelayVariablesInAllowedPosition'>;
}
declare module 'vscode-apollo-relay/dist/utils.js' {
  declare module.exports: $Exports<'vscode-apollo-relay/dist/utils'>;
}
