export default {
  COMMENT_SYSTEM_NONE: 0,
  COMMENT_SYSTEM_SIMPLE: 1,
  COMMENT_SYSTEM_BOTH: 2,

  RECEIVE_ARGUMENTS: 'RECEIVE_ARGUMENTS',

  CHANGE_ARGUMENTS_SORT_ORDER: 'CHANGE_ARGUMENTS_SORT_ORDER',

  CREATE_ARGUMENT_SUCCESS: 'CREATE_ARGUMENT_SUCCES',
  CREATE_ARGUMENT_FAILURE: 'CREATE_ARGUMENT_FAILURE',

  UPDATE_ARGUMENT_SUCCESS: 'UPDATE_ARGUMENT_SUCCESS',
  UPDATE_ARGUMENT_FAILURE: 'UPDAE_ARGUMENT_FAILURE',
};
