export const DEFAULT_IDEAS_PAGINATION = 8;
export const SET_IDEAS_PAGINATION = 'SET_IDEAS_PAGINATION';
export const INIT_IDEAS_COUNTS = 'INIT_IDEAS_COUNTS';
export const INIT_IDEA = 'INIT_IDEA';
export const INIT_IDEAS = 'INIT_IDEAS';

export const CHANGE_IDEAS_PAGE = 'CHANGE_IDEAS_PAGE';
export const CHANGE_IDEAS_ORDER = 'CHANGE_IDEAS_ORDER';
export const CHANGE_IDEAS_THEME = 'CHANGE_IDEAS_THEME';
export const CHANGE_IDEAS_SEARCH_TERMS = 'CHANGE_IDEAS_SEARCH_TERMS';

export const CREATE_IDEA_SUCCESS = 'CREATE_IDEA_SUCCESS';
export const CREATE_IDEA_FAILURE = 'CREATE_IDEA_FAILURE';
export const UPDATE_IDEA_SUCCESS = 'UPDATE_IDEA_SUCCESS';
export const UPDATE_IDEA_FAILURE = 'UPDATE_IDEA_FAILURE';
export const DELETE_IDEA_SUCCESS = 'DELETE_IDEA_SUCCESS';
export const DELETE_IDEA_FAILURE = 'DELETE_IDEA_FAILURE';

export const REPORT_IDEA_SUCCESS = 'REPORT_IDEA_SUCCESS';

export const CREATE_IDEA_VOTE_FAILURE = 'CREATE_IDEA_VOTE_FAILURE';

export const RECEIVE_IDEAS = 'RECEIVE_IDEAS';
export const RECEIVE_IDEA = 'RECEIVE_IDEA';
export const RECEIVE_IDEA_VOTES = 'RECEIVE_IDEA_VOTES';
