export default {
  RECEIVE_OPINION: 'RECEIVE_OPINION',
  RECEIVE_VERSIONS: 'RECEIVE_VERSIONS',
  RECEIVE_SOURCES: 'RECEIVE_SOURCES',
  RECEIVE_ARGUMENTS: 'RECEIVE_ARGUMENTS',

  CREATE_OPINION_VOTE: 'CREATE_OPINION_VOTE',
  CREATE_OPINION_VOTE_SUCCESS: 'CREATE_OPINION_VOTE_SUCCESS',
  CREATE_OPINION_VOTE_FAILURE: 'CREATE_OPINION_VOTE_FAILURE',

  CREATE_OPINION_VERSION: 'CREATE_OPINION_VERSION',
  UPDATE_OPINION_VERSION: 'UPDATE_OPINION_VERSION',

  CREATE_OPINION_VERSION_VOTE: 'CREATE_OPINION_VERSION_VOTE',
  CREATE_OPINION_VERSION_VOTE_SUCCESS: 'CREATE_OPINION_VERSION_VOTE_SUCCESS',
  CREATE_OPINION_VERSION_VOTE_FAILURE: 'CREATE_OPINION_VERSION_VOTE_FAILURE',
};
