export default {
  RECEIVE_SOURCES: 'RECEIVE_SOURCES',
  CREATE_SOURCE_SUCCESS: 'CREATE_SOURCE_SUCCESS',
  CREATE_SOURCE_FAILURE: 'CREATE_SOURCE_FAILURE',
  UPDATE_SOURCE_SUCCESS: 'UPDATE_SOURCE_SUCCESS',
  UPDATE_SOURCE_FAILURE: 'UPDATE_SOURCE_FAILURE',
};
