export default {
  RECEIVE_OPINION: 'RECEIVE_OPINION',

  UPDATE_OPINION_SUCCESS: 'UPDATE_OPINION_SUCCESS',
  UPDATE_OPINION_FAILURE: 'UPDATE_OPINION_FAILURE',

  CREATE_OPINION_VERSION: 'CREATE_OPINION_VERSION',
  UPDATE_OPINION_VERSION: 'UPDATE_OPINION_VERSION',

  CREATE_OPINION_VOTE: 'CREATE_OPINION_VOTE',
  DELETE_OPINION_VOTE: 'DELETE_OPINION_VOTE',

  RECEIVE_VERSIONS: 'RECEIVE_VERSIONS',
  RECEIVE_SOURCES: 'RECEIVE_SOURCES',
  RECEIVE_ARGUMENTS: 'RECEIVE_ARGUMENTS',

  CREATE_ARGUMENT: 'CREATE_ARGUMENT',
  CREATE_ARGUMENT_SUCCESS: 'CREATE_ARGUMENT_SUCCES',
  CREATE_ARGUMENT_FAILURE: 'CREATE_ARGUMENT_FAILURE',
};
