export default {
  CREATE_OPINION_VERSION_VOTE: 'CREATE_OPINION_VERSION_VOTE',
  CREATE_OPINION_VERSION_VOTE_SUCCESS: 'CREATE_OPINION_VERSION_VOTE_SUCCESS',
  CREATE_OPINION_VERSION_VOTE_FAILURE: 'CREATE_OPINION_VERSION_VOTE_FAILURE',

  CREATE_OPINION_VERSION: 'CREATE_OPINION_VERSION',
};
