// @flow
export const RECEIVE_LINKS = 'RECEIVE_LINKS';
export const CREATE_OPINION_LINK_SUCCESS = 'CREATE_OPINION_LINK_SUCCESS';
export const CREATE_OPINION_LINK_FAILURE = 'CREATE_OPINION_LINK_FAILURE';
