export default {
  RECEIVE_OPINION: 'RECEIVE_OPINION',

  UPDATE_OPINION_SUCCESS: 'UPDATE_OPINION_SUCCESS',
  UPDATE_OPINION_FAILURE: 'UPDATE_OPINION_FAILURE',

  DELETE_OPINION_SUCCESS: 'DELETE_OPINION_SUCCESS',
  DELETE_OPINION_FAILURE: 'DELETE_OPINION_FAILURE',

  CREATE_OPINION_VOTE: 'CREATE_OPINION_VOTE',
  DELETE_OPINION_VOTE: 'DELETE_OPINION_VOTE',

  RECEIVE_VERSIONS: 'RECEIVE_VERSIONS',
  RECEIVE_SOURCES: 'RECEIVE_SOURCES',
  RECEIVE_LINKS: 'RECEIVE_LINKS',

  CREATE_OPINION_VERSION_SUCCESS: 'CREATE_OPINION_VERSION_SUCCESS',
  CREATE_OPINION_VERSION_FAILURE: 'CREATE_OPINION_VERSION_FAILURE',

  UPDATE_OPINION_VERSION_SUCCESS: 'UPDATE_OPINION_VERSION_SUCCESS',
  UPDATE_OPINION_VERSION_FAILURE: 'UPDATE_OPINION_VERSION_FAILURE',

  DELETE_OPINION_VERSION_SUCCESS: 'DELETE_OPINION_VERSION_SUCCESS',
  DELETE_OPINION_VERSION_FAILURE: 'DELETE_OPINION_VERSION_FAILURE',
};
