export default {
  CREATE_OPINION_LINK_SUCCESS: 'CREATE_OPINION_LINK_SUCCESS',
  CREATE_OPINION_LINK_FAILURE: 'CREATE_OPINION_LINK_FAILURE',
  UPDATE_OPINION_LINK_SUCCESS: 'UPDATE_OPINION_LINK_SUCCESS',
  UPDATE_OPINION_LINK_FAILURE: 'UPDATE_OPINION_LINK_FAILURE',
};
