export const RECEIVE_SOURCES = 'RECEIVE_SOURCES';
export const CREATE_SOURCE_SUCCESS = 'CREATE_SOURCE_SUCCESS';
export const CREATE_SOURCE_FAILURE = 'CREATE_SOURCE_FAILURE';
export const UPDATE_SOURCE_SUCCESS = 'UPDATE_SOURCE_SUCCESS';
export const UPDATE_SOURCE_FAILURE = 'UPDATE_SOURCE_FAILURE';
