export default {
  RECEIVE_PROPOSAL: 'RECEIVE_PROPOSAL',
  RECEIVE_PROPOSALS: 'RECEIVE_PROPOSALS',

  CREATE_PROPOSAL_VOTE: 'CREATE_PROPOSAL_VOTE',
  CREATE_PROPOSAL_VOTE_SUCCESS: 'CREATE_PROPOSAL_VOTE_SUCCESS',
  CREATE_PROPOSAL_VOTE_FAILURE: 'CREATE_PROPOSAL_VOTE_FAILURE',

  DELETE_PROPOSAL_VOTE: 'DELETE_PROPOSAL_VOTE',
  DELETE_PROPOSAL_VOTE_SUCCESS: 'DELETE_PROPOSAL_VOTE_SUCCESS',
  DELETE_PROPOSAL_VOTE_FAILURE: 'DELETE_PROPOSAL_VOTE_FAILURE',

  RECEIVE_PROPOSAL_COMMENTS: 'RECEIVE_PROPOSAL_COMMENTS',

  CREATE_PROPOSAL_COMMENT: 'CREATE_PROPOSAL_COMMENT',
  CREATE_PROPOSAL_COMMENT_SUCCESS: 'CREATE_PROPOSAL_COMMENT_SUCCESS',
  CREATE_PROPOSAL_COMMENT_FAILURE: 'CREATE_PROPOSAL_COMMENT_FAILURE',
};
