export default {
  RECEIVE_PROPOSAL: 'RECEIVE_PROPOSAL',
  RECEIVE_PROPOSAL_VOTES: 'RECEIVE_PROPOSAL_VOTES',
  RECEIVE_PROPOSALS: 'RECEIVE_PROPOSALS',

  INIT_PROPOSAL: 'INIT_PROPOSAL',
  SUBMIT_PROPOSAL: 'SUBMIT_PROPOSAL',
  VALIDATION_FAILURE: 'VALIDATION_FAILURE',

  CREATE_PROPOSAL_SUCCESS: 'CREATE_PROPOSAL_SUCCESS',
  CREATE_PROPOSAL_FAILURE: 'CREATE_PROPOSAL_FAILURE',
  UPDATE_PROPOSAL_SUCCESS: 'UPDATE_PROPOSAL_SUCCESS',
  UPDATE_PROPOSAL_FAILURE: 'UPDATE_PROPOSAL_FAILURE',
  DELETE_PROPOSAL_SUCCESS: 'DELETE_PROPOSAL_SUCCESS',
  DELETE_PROPOSAL_FAILURE: 'DELETE_PROPOSAL_FAILURE',

  INIT_PROPOSAL_VOTES: 'INIT_PROPOSAL_VOTES',
  CREATE_PROPOSAL_VOTE: 'CREATE_PROPOSAL_VOTE',
  CREATE_PROPOSAL_VOTE_SUCCESS: 'CREATE_PROPOSAL_VOTE_SUCCESS',
  CREATE_PROPOSAL_VOTE_FAILURE: 'CREATE_PROPOSAL_VOTE_FAILURE',

  DELETE_PROPOSAL_VOTE: 'DELETE_PROPOSAL_VOTE',
  DELETE_PROPOSAL_VOTE_SUCCESS: 'DELETE_PROPOSAL_VOTE_SUCCESS',
  DELETE_PROPOSAL_VOTE_FAILURE: 'DELETE_PROPOSAL_VOTE_FAILURE',

  VOTE_TYPE_DISABLED: 0,
  VOTE_TYPE_SIMPLE: 1,
  VOTE_TYPE_BUDGET: 2,

  CHANGE_PAGE: 'CHANGE_PAGE',
  CHANGE_FILTERS: 'CHANGE_FILTERS',
  CHANGE_ORDER: 'CHANGE_ORDER',
  CHANGE_SEARCH_TERMS: 'CHANGE_SEARCH_TERMS',

  PROPOSAL_PAGINATION: 50,
  PROPOSAL_VOTES_TO_SHOW: 6,
};
