export default {
  RECEIVE_PROPOSAL: 'RECEIVE_PROPOSAL',
  RECEIVE_PROPOSALS: 'RECEIVE_PROPOSALS',

  CREATE_PROPOSAL_VOTE: 'CREATE_PROPOSAL_VOTE',
  CREATE_PROPOSAL_VOTE_SUCCESS: 'CREATE_PROPOSAL_VOTE_SUCCESS',
  CREATE_PROPOSAL_VOTE_FAILURE: 'CREATE_PROPOSAL_VOTE_FAILURE',

  DELETE_PROPOSAL_VOTE: 'DELETE_PROPOSAL_VOTE',
  DELETE_PROPOSAL_VOTE_SUCCESS: 'DELETE_PROPOSAL_VOTE_SUCCESS',
  DELETE_PROPOSAL_VOTE_FAILURE: 'DELETE_PROPOSAL_VOTE_FAILURE',

  CHANGE_PAGE: 'CHANGE_PAGE',
  CHANGE_FILTERS: 'CHANGE_FILTERS',
  CHANGE_ORDER: 'CHANGE_ORDER',

  PROPOSAL_PAGINATION: 20,
};
