export default {
  RECEIVE_COUNT: 'RECEIVE_COUNT',

  RECEIVE_ELEMENTS: 'RECEIVE_ELEMENTS',
  RECEIVE_ELEMENTS_SUCCESS: 'RECEIVE_ELEMENTS_SUCCESS',
  RECEIVE_ELEMENTS_FAILURE: 'RECEIVE_ELEMENTS_FAILURE',

  RECEIVE_ELEMENT: 'RECEIVE_ELEMENT',
  RECEIVE_ELEMENT_SUCCESS: 'RECEIVE_ELEMENT_SUCCESS',
  RECEIVE_ELEMENT_FAILURE: 'RECEIVE_ELEMENT_FAILURE',

  EXPAND_TREE_ITEM: 'EXPAND_TREE_ITEM',
  SELECT_NAV_ITEM: 'SELECT_NAV_ITEM',

  ARCHIVE_ELEMENT: 'ARCHIVE_ELEMENT',
  UPDATE_ELEMENT: 'UPDATE_ELEMENT',
  NOTE_ELEMENT: 'NOTE_ELEMENT',
  COMMENT_ELEMENT: 'COMMENT_ELEMENT',
  NAME_ELEMENT: 'NAME_ELEMENT',
  MOVE_ELEMENT: 'MOVE_ELEMENT',
  DIVIDE_ELEMENT: 'DIVIDE_ELEMENT',

  UPDATE_ELEMENT_SUCCESS: 'UPDATE_ELEMENT_SUCCESS',
  UPDATE_ELEMENT_FAILURE: 'UPDATE_ELEMENT_FAILURE',
  CREATE_ELEMENT: 'CREATE_ELEMENT',
  CREATE_ELEMENT_SUCCESS: 'CREATE_ELEMENT_SUCCESS',
  CREATE_ELEMENT_FAILURE: 'CREATE_ELEMENT_FAILURE',
};
