export default {
  RECEIVE_COUNT: 'RECEIVE_COUNT',
  RECEIVE_ELEMENTS: 'RECEIVE_ELEMENTS',
  RECEIVE_ELEMENT: 'RECEIVE_ELEMENT',
  ARCHIVE_ELEMENT: 'ARCHIVE_ELEMENT',
  UPDATE_ELEMENT: 'UPDATE_ELEMENT',
  NOTE_ELEMENT: 'NOTE_ELEMENT',
  DISABLE_ELEMENT: 'DISABLE_ELEMENT',
  MOVE_ELEMENT: 'MOVE_ELEMENT',
  UPDATE_ELEMENT_SUCCESS: 'UPDATE_ELEMENT_SUCCESS',
  UPDATE_ELEMENT_FAILURE: 'UPDATE_ELEMENT_FAILURE',
};
