#!/bin/bash

rm -rf app/cache/prod/*
chown -R capco:capco /var/www/app/cache
chown -R capco:capco /var/www/app/logs
chown -R capco:capco /var/www/web/media

su capco <<'EOF'
sleep 10
cd       /var/www
RESULT=`php app/console doctrine:migrations:status --env=prod 2>&1 | grep -o "Unknown database" | wc -l`
if [ "$RESULT" != "0" ]; then
    php app/console doctrine:database:create --env=prod --if-not-exists
    php app/console doctrine:migrations:migrate --env=prod --no-interaction
    php app/console capco:load-base-data --force --env=prod --no-interaction
    php app/console cache:warmup --env=prod --no-debug
else
    php app/console doctrine:migrations:migrate --env=prod --no-interaction
    php app/console cache:warmup --env=prod --no-debug
fi

EOF

exec php5-fpm -y /etc/service/php-fpm/fpm.conf -O
