export { default as DebatePage } from './debate'
export { default as QuestionnairePage } from './questionnaire'
export { default as ProjectsPage } from './projects'
export { default as AdminProjectsListPage } from './admin/projectsList'
export { default as AdminProjectPage } from './admin/project'
export { default as AdminDashboardPage } from './admin/dashboard'
