<?php

namespace Capco\AdminBundle\Admin;

use Capco\AppBundle\Elasticsearch\Indexer;
use Capco\AppBundle\Entity\Theme;
use Capco\AppBundle\Provider\MediaProvider;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Form\Type\ModelAutocompleteType;
use Sonata\AdminBundle\Form\Type\ModelListType;
use Sonata\AdminBundle\Object\Metadata;
use Sonata\AdminBundle\Object\MetadataInterface;
use Sonata\AdminBundle\Show\ShowMapper;
use Sonata\DoctrineORMAdminBundle\Filter\ModelAutocompleteFilter;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class ThemeAdmin extends AbstractAdmin
{
    protected ?string $classnameLabel = 'theme';
    protected array $datagridValues = [
        '_sort_order' => 'ASC',
        '_sort_by' => 'position',
    ];
    private Indexer $indexer;
    private MediaProvider $mediaProvider;

    public function __construct(
        string $code,
        string $class,
        string $baseControllerName,
        Indexer $indexer,
        MediaProvider $mediaProvider
    ) {
        parent::__construct($code, $class, $baseControllerName);
        $this->indexer = $indexer;
        $this->mediaProvider = $mediaProvider;
    }

    // For mosaic view
    public function getObjectMetadata($object): MetadataInterface
    {
        $media = $object->getMedia();
        if ($media) {
            return new Metadata(
                $object->getTitle(),
                null,
                $this->mediaProvider->generatePublicUrl(
                    $media,
                    $this->mediaProvider->getFormatName($media, 'form')
                )
            );
        }

        return parent::getObjectMetadata($object);
    }

    public function getFeatures(): array
    {
        return ['themes'];
    }

    public function preRemove($object): void
    {
        $this->indexer->remove(\get_class($object), $object->getId());
        $this->indexer->finishBulk();
        parent::preRemove($object); // TODO: Change the autogenerated stub
    }

    protected function configureDatagridFilters(DatagridMapper $filter): void
    {
        $filter
            ->add('title', null, [
                'label' => 'global.title',
            ])
            ->add('position', null, [
                'label' => 'global.position',
            ])
            ->add('isEnabled', null, [
                'label' => 'global.published',
            ])
            ->add('projects', null, [
                'label' => 'global.participative.project',
            ])
            ->add('events', null, [
                'label' => 'global.events',
            ])
            ->add('posts', null, [
                'label' => 'global.articles',
            ])
            ->add('createdAt', null, [
                'label' => 'global.creation',
            ])
            ->add('updatedAt', null, [
                'label' => 'global.maj',
            ])
            ->add('author', ModelAutocompleteFilter::class, [
                'field_options' => [
                    'label' => 'global.author',
                    'property' => 'email,username',
                    'to_string_callback' => function ($entity, $property) {
                        return $entity->getEmail() . ' - ' . $entity->getUsername();
                    },
                ],
            ])
        ;
    }

    protected function configureListFields(ListMapper $list): void
    {
        $list
            ->addIdentifier('title', null, [
                'label' => 'global.title',
                'route' => [
                    'name' => 'edit',
                ],
            ])
            ->add('author', null, [
                'label' => 'global.author',
            ])
            ->add('status', null, [
                'label' => 'global.status',
                'template' => '@CapcoAdmin/Theme/status_list_field.html.twig',
                'statusesLabels' => Theme::$statusesLabels,
            ])
            ->add('position', null, [
                'label' => 'global.position',
            ])
            ->add('events', null, [
                'label' => 'global.events',
                'template' => '@CapcoAdmin/Theme/events_count_list_field.html.twig',
            ])
            ->add('posts', null, [
                'label' => 'global.articles',
                'template' => '@CapcoAdmin/Theme/posts_count_list_field.html.twig',
            ])
            ->add('isEnabled', null, [
                'editable' => true,
                'label' => 'global.published',
            ])
            ->add('updatedAt', 'datetime', [
                'label' => 'global.maj',
            ])
            ->add('_action', 'actions', [
                'label' => 'link_actions',
                'actions' => [
                    'show' => [],
                    'edit' => [],
                    'delete' => [],
                ],
            ])
        ;
    }

    protected function configureFormFields(FormMapper $form): void
    {
        $editMode = $this->hasSubject() && $this->getSubject()->getId();

        $form->add('title', TextType::class, [
            'label' => 'global.title',
            'required' => true,
        ]);

        if ($editMode) {
            $form->add('slug', TextType::class, [
                'disabled' => true,
                'attr' => ['readonly' => true],
                'label' => 'global.link',
            ]);
        }
        $form
            ->add('author', ModelAutocompleteType::class, [
                'label' => 'global.author',
                'property' => 'username,email',
                'to_string_callback' => function ($entity) {
                    return $entity->getEmail() . ' - ' . $entity->getUsername();
                },
            ])
            ->add('isEnabled', null, [
                'label' => 'global.published',
                'required' => false,
            ])
            ->add('position', IntegerType::class, [
                'label' => 'global.position',
            ])
            ->add('teaser', TextareaType::class, [
                'label' => 'global.subtitle',
                'required' => false,
            ])
            ->add('body', CKEditorType::class, [
                'label' => 'global.description',
                'config_name' => 'admin_editor',
                'required' => false,
            ])
            ->add('status', ChoiceType::class, [
                'label' => 'global.status',
                'choices' => Theme::$statusesLabels,
                'translation_domain' => 'CapcoAppBundle',
                'required' => false,
                'placeholder' => 'global.no_status',
            ])
            ->add('media', ModelListType::class, [
                'required' => false,
                'label' => 'global.image',
            ])
            ->end()
        ;
        $form
            ->with('admin.fields.page.advanced')
            ->add('metaDescription', TextType::class, [
                'label' => 'global.meta.description',
                'required' => false,
                'help' => 'admin.help.metadescription',
            ])
            ->add('customCode', null, [
                'label' => 'admin.customcode',
                'required' => false,
                'help' => 'admin.help.customcode',
                'attr' => [
                    'rows' => 10,
                    'placeholder' => '<script type="text/javascript"> </script>',
                ],
            ])
            ->end()
        ;
    }

    protected function configureShowFields(ShowMapper $show): void
    {
        $show
            ->add('title', null, [
                'label' => 'global.title',
            ])
            ->add('isEnabled', null, [
                'label' => 'global.published',
            ])
            ->add('teaser', null, [
                'label' => 'global.subtitle',
            ])
            ->add('body', null, [
                'label' => 'global.description',
            ])
            ->add('status', null, [
                'label' => 'global.status',
                'template' => '@CapcoAdmin/Theme/status_show_field.html.twig',
                'statusesLabels' => array_flip(Theme::$statusesLabels),
            ])
            ->add('position', null, [
                'label' => 'global.position',
            ])
            ->add('author', null, [
                'label' => 'global.author',
            ])
            ->add('projects', null, [
                'label' => 'global.participative.project',
            ])
            ->add('events', null, [
                'label' => 'global.events',
            ])
            ->add('posts', null, [
                'label' => 'global.articles',
            ])
            ->add('media', null, [
                'template' => '@CapcoAdmin/Theme/media_show_field.html.twig',
                'label' => 'global.image',
            ])
            ->add('createdAt', null, [
                'label' => 'global.creation',
            ])
            ->add('updatedAt', null, [
                'label' => 'global.maj',
            ])
        ;
    }

    protected function configure(): void
    {
        $this->setTemplate('edit', '@CapcoAdmin/CRUD/edit.html.twig');
    }
}
