describe('Log in & Log out', () => {
  describe('Logged-in vote', () => {
    before(() => {
      cy.task('db:restore')
      cy.task('enable:feature', 'profiles')
    })
    it('should show a login button and no logout button if not connected', () => {
      cy.visit('/legal')
      cy.get('#login-button', { timeout: 15000 }).should('exist')
      cy.get('#logout-button').should('not.exist')
    })
    it('should be possible to log in as user', () => {
      cy.interceptGraphQLOperation({ operationName: 'NavbarRightQuery' })
      cy.visit('/legal')
      cy.loginAs('user')
      cy.get('#navbar-username', { timeout: 15000 }).contains('user').should('exist')
      cy.get('#login-button').should('not.exist')
      cy.get('#navbar-username').contains('user').click()
      cy.get('#logout-button').should('exist')
      cy.get('.user-profile').contains('global.administration').should('not.exist')
      cy.get('.user-profile').contains('user.profile.title').should('exist')
      cy.get('.user-profile').contains('global.params').should('exist')
    })
    it('should be possible to log in as admin and access administration', () => {
      cy.interceptGraphQLOperation({ operationName: 'NavbarRightQuery' })
      cy.visit('/legal')
      cy.loginAs('admin')
      cy.get('#navbar-username', { timeout: 15000 }).contains('admin').should('exist')
      cy.get('#login-button').should('not.exist')
      cy.get('#navbar-username').contains('admin').click()
      cy.get('#logout-button').should('exist')
      cy.get('.user-profile').contains('global.administration').should('exist')
      cy.get('.user-profile').contains('user.profile.title').should('exist')
      cy.get('.user-profile').contains('global.params').should('exist')
    })
    it('should be possible to log out as user', () => {
      cy.interceptGraphQLOperation({ operationName: 'NavbarRightQuery' })
      cy.visit('/legal')
      cy.loginAs('user')
      cy.get('#navbar-username', { timeout: 15000 }).contains('user').should('exist')
      cy.get('#navbar-username').contains('user').click()
      cy.get('.user-profile').contains('global.logout').click()
      cy.get('#login-button').should('exist')
      cy.get('#logout-button').should('not.exist')
    })
  })
})
