// @flow
import type { Questions, ResponsesInReduxForm } from '~/components/Form/Form.type';

export const simple: Questions = [
  {
    id: 'UXVlc3Rpb246NDg1',
    __typename: 'SimpleQuestion',
    title: 'Question 1',
    number: 1,
    private: false,
    hidden: false,
    position: 1,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'text',
  },
  {
    id: 'UXVlc3Rpb246NDg0',
    __typename: 'SimpleQuestion',
    title: 'Question 2',
    number: 2,
    private: false,
    hidden: false,
    position: 2,
    required: true,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'text',
  },
];

export const onlyAlwaysJump: Questions = [
  {
    id: 'UXVlc3Rpb246NDg1',
    __typename: 'SimpleQuestion',
    title: 'Question 1',
    number: 1,
    private: false,
    hidden: false,
    position: 3,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: {
      id: 'UXVlc3Rpb246NDg0',
      title: 'Question 2',
      number: 2,
    },
    description: null,
    type: 'text',
  },
  {
    id: 'UXVlc3Rpb246NDg0',
    __typename: 'SimpleQuestion',
    title: 'Question 2',
    number: 2,
    private: false,
    hidden: false,
    position: 4,
    required: true,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'text',
  },
];

export const manyAlwaysJump: Questions = [
  {
    id: 'UXVlc3Rpb246NDg3',
    __typename: 'MultipleChoiceQuestion',
    title: 'Question 1',
    number: 1,
    private: false,
    hidden: false,
    position: 95,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: {
      id: 'UXVlc3Rpb246NDky',
      title: 'Question 2',
      number: 2,
    },
    description: null,
    type: 'select',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 3,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzYyMTgtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Jump to question 2',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzY2NGMtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Useless',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzY5OWMtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Fais rien',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NDky',
    __typename: 'SimpleQuestion',
    title: 'Question 2',
    number: 2,
    private: false,
    hidden: false,
    position: 96,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: {
      id: 'UXVlc3Rpb246NDkx',
      title: 'Question 3',
      number: 3,
    },
    description: null,
    type: 'text',
  },
  {
    id: 'UXVlc3Rpb246NDkx',
    __typename: 'SimpleQuestion',
    title: 'Question 3',
    number: 3,
    private: false,
    hidden: false,
    position: 97,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: {
      id: 'UXVlc3Rpb246NDk1',
      title: 'Question 1.1',
      number: 4,
    },
    description: null,
    type: 'text',
  },
  {
    id: 'UXVlc3Rpb246NDk2',
    __typename: 'SectionQuestion',
    title: 'Section 1',
    number: 4,
    private: false,
    hidden: false,
    position: 98,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'section',
  },
  {
    id: 'UXVlc3Rpb246NDk1',
    __typename: 'SimpleQuestion',
    title: 'Question 1.1',
    number: 4,
    private: false,
    hidden: false,
    position: 99,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'text',
  },
];

export const onlyJump: Questions = [
  {
    id: 'UXVlc3Rpb246NDg3',
    __typename: 'MultipleChoiceQuestion',
    title: 'Question 1',
    number: 1,
    private: false,
    hidden: false,
    position: 22,
    required: false,
    helpText: null,
    jumps: [
      {
        id: 'c3f09535-6cf8-11ea-9d72-0242ac110006',
        origin: {
          id: 'UXVlc3Rpb246NDg3',
        },
        destination: {
          id: 'UXVlc3Rpb246NDg4',
          title: 'Question 3',
          number: 3,
        },
        conditions: [
          {
            id: 'c3f09b13-6cf8-11ea-9d72-0242ac110006',
            operator: 'IS',
            question: {
              id: 'UXVlc3Rpb246NDg3',
              title: 'Question 1',
              type: 'select',
            },
            value: {
              id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzYyMTgtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
              title: 'Jump to question 3',
            },
          },
        ],
      },
    ],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'select',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 3,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzYyMTgtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Jump to question 3',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzY2NGMtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Useless',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzY5OWMtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Fais rien',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NDg4',
    __typename: 'MultipleChoiceQuestion',
    title: 'Question 3',
    number: 3,
    private: false,
    hidden: false,
    position: 24,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'select',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 2,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YTZkZDk3NjctNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Jump to question 4',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YTZkZDljNDItNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Sert à rien',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
];

export const jumpThenAlwaysJump: Questions = [
  {
    id: 'UXVlc3Rpb246NDg3',
    __typename: 'MultipleChoiceQuestion',
    title: 'Question 1',
    number: 1,
    private: false,
    hidden: false,
    position: 40,
    required: false,
    helpText: null,
    jumps: [
      {
        id: 'c3f09535-6cf8-11ea-9d72-0242ac110006',
        origin: {
          id: 'UXVlc3Rpb246NDg3',
        },
        destination: {
          id: 'UXVlc3Rpb246NDg4',
          title: 'Question 3',
          number: 2,
        },
        conditions: [
          {
            id: 'c3f09b13-6cf8-11ea-9d72-0242ac110006',
            operator: 'IS',
            question: {
              id: 'UXVlc3Rpb246NDg3',
              title: 'Question 1',
              type: 'select',
            },
            value: {
              id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzYyMTgtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
              title: 'Jump to question 3',
            },
          },
        ],
      },
    ],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'select',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 3,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzYyMTgtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Jump to question 3',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzY2NGMtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Useless',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzY5OWMtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Fais rien',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NDg4',
    __typename: 'MultipleChoiceQuestion',
    title: 'Question 3',
    number: 2,
    private: false,
    hidden: false,
    position: 41,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: {
      id: 'UXVlc3Rpb246NDkw',
      title: 'Question 4',
      number: 3,
    },
    description: null,
    type: 'select',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 2,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YTZkZDk3NjctNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Jump to question 4',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YTZkZDljNDItNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Sert à rien',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NDkw',
    __typename: 'SimpleQuestion',
    title: 'Question 4',
    number: 3,
    private: false,
    hidden: false,
    position: 42,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'text',
  },
];

export const manySimpleAndManyJump: Questions = [
  {
    id: 'UXVlc3Rpb246NDg3',
    __typename: 'MultipleChoiceQuestion',
    title: 'Question 1',
    number: 1,
    private: false,
    hidden: false,
    position: 58,
    required: false,
    helpText: null,
    jumps: [
      {
        id: 'c3f09535-6cf8-11ea-9d72-0242ac110006',
        origin: {
          id: 'UXVlc3Rpb246NDg3',
        },
        destination: {
          id: 'UXVlc3Rpb246NDg4',
          title: 'Question 2',
          number: 2,
        },
        conditions: [
          {
            id: 'c3f09b13-6cf8-11ea-9d72-0242ac110006',
            operator: 'IS',
            question: {
              id: 'UXVlc3Rpb246NDg3',
              title: 'Question 1',
              type: 'select',
            },
            value: {
              id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzYyMTgtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
              title: 'Jump to question 2',
            },
          },
        ],
      },
    ],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'select',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 3,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzYyMTgtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Jump to question 2',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzY2NGMtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Useless',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzY5OWMtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Fais rien',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NDg4',
    __typename: 'MultipleChoiceQuestion',
    title: 'Question 2',
    number: 2,
    private: false,
    hidden: false,
    position: 59,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'select',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 2,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YTZkZDk3NjctNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Jump to question 4',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YTZkZDljNDItNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Sert à rien',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NDky',
    __typename: 'SimpleQuestion',
    title: 'Question 3',
    number: 3,
    private: false,
    hidden: false,
    position: 60,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'text',
  },
  {
    id: 'UXVlc3Rpb246NDkz',
    __typename: 'MultipleChoiceQuestion',
    title: 'Question 4',
    number: 4,
    private: false,
    hidden: false,
    position: 61,
    required: false,
    helpText: null,
    jumps: [
      {
        id: 'f3016117-6cfd-11ea-9d72-0242ac110006',
        origin: {
          id: 'UXVlc3Rpb246NDkz',
        },
        destination: {
          id: 'UXVlc3Rpb246NDkx',
          title: 'Question 5',
          number: 5,
        },
        conditions: [
          {
            id: 'f301671b-6cfd-11ea-9d72-0242ac110006',
            operator: 'IS',
            question: {
              id: 'UXVlc3Rpb246NDkz',
              title: 'Question 4',
              type: 'select',
            },
            value: {
              id: 'UXVlc3Rpb25DaG9pY2U6YmQ4ZDM4NjItNmNmZC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
              title: 'Afficher question 5',
            },
          },
        ],
      },
    ],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'select',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 2,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YmQ4ZDM4NjItNmNmZC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Afficher question 5',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YmQ4ZDNjZTctNmNmZC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Nothing',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NDkx',
    __typename: 'SimpleQuestion',
    title: 'Question 5',
    number: 5,
    private: false,
    hidden: false,
    position: 62,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'text',
  },
  {
    id: 'UXVlc3Rpb246NDk0',
    __typename: 'SimpleQuestion',
    title: 'Question 6',
    number: 6,
    private: false,
    hidden: false,
    position: 63,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'text',
  },
];

export const allTypeQuestions: Questions = [
  {
    id: 'UXVlc3Rpb246NDg3',
    __typename: 'MultipleChoiceQuestion',
    title: 'Capital de la France ?',
    number: 1,
    private: false,
    hidden: false,
    position: 150,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'select',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 3,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzYyMTgtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Paris',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzY2NGMtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Lyon',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzY5OWMtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Strasbourg',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NDk4',
    __typename: 'SimpleQuestion',
    title: 'Comment tu vas ?',
    number: 2,
    private: false,
    hidden: false,
    position: 151,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'text',
  },
  {
    id: 'UXVlc3Rpb246NDk3',
    __typename: 'SimpleQuestion',
    title: "De quelle couleur est le cheval blanc d'Henry IV ?",
    number: 3,
    private: false,
    hidden: false,
    position: 152,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'textarea',
  },
  {
    id: 'UXVlc3Rpb246NTAw',
    __typename: 'SimpleQuestion',
    title: 'Petit du loup ?',
    number: 4,
    private: false,
    hidden: false,
    position: 153,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'editor',
  },
  {
    id: 'UXVlc3Rpb246NDk5',
    __typename: 'SimpleQuestion',
    title: "Combien j'ai de doigt ?",
    number: 5,
    private: false,
    hidden: false,
    position: 154,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'number',
  },
  {
    id: 'UXVlc3Rpb246NTAx',
    __typename: 'MediaQuestion',
    title: 'Envoie ton CV',
    number: 6,
    private: false,
    hidden: false,
    position: 155,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'medias',
  },
  {
    id: 'UXVlc3Rpb246NTAy',
    __typename: 'MultipleChoiceQuestion',
    title: 'Coche la case vert',
    number: 7,
    private: false,
    hidden: false,
    position: 156,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'button',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 3,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTFmZjUwZWQtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Je suis vert',
            description: null,
            color: 'SUCCESS',
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTFmZjU1MGItNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Je suis orange',
            description: null,
            color: 'WARNING',
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTFmZjU4NTYtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Je suis rouge',
            description: null,
            color: 'DANGER',
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NTAz',
    __typename: 'MultipleChoiceQuestion',
    title: 'Qui a dit "Je suis ton père" ?',
    number: 8,
    private: false,
    hidden: false,
    position: 157,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'radio',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 3,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YWIyZTZmNjAtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Yoda',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YWIyZTczYzAtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Dark Vador',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YWIyZTc2ZDktNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Jean pierre Foucault',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NTA0',
    __typename: 'MultipleChoiceQuestion',
    title: 'Tes sports préférés ?',
    number: 9,
    private: false,
    hidden: false,
    position: 158,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'checkbox',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 4,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGFiNTQtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Tennis',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGFmYTUtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Canoë Kayak',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGIzMDQtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Golf',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGI2MTMtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Football',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NTA1',
    __typename: 'MultipleChoiceQuestion',
    title: 'Fruits préférés ?',
    number: 10,
    private: false,
    hidden: false,
    position: 159,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'ranking',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 3,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6ZDUzZWJhMmItNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Pomme',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6ZDUzZWJkZjctNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Poire',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6ZDUzZWMxMWUtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Fraise',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NTA2',
    __typename: 'MajorityQuestion',
    title: 'Comment vas-tu ?',
    number: 11,
    private: false,
    hidden: false,
    position: 160,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'majority',
    randomQuestionChoices: false,
  },
];

export const allTypeQuestionsWithRule: Questions = [
  {
    id: 'UXVlc3Rpb246NDg3',
    __typename: 'MultipleChoiceQuestion',
    title: 'Capital de la France ?',
    number: 1,
    private: false,
    hidden: false,
    position: 150,
    required: true,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'select',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 3,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzYyMTgtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Paris',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzY2NGMtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Lyon',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTVmNzY5OWMtNmNmOC0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Strasbourg',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NDk4',
    __typename: 'SimpleQuestion',
    title: 'Comment tu vas ?',
    number: 2,
    private: false,
    hidden: false,
    position: 151,
    required: true,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'text',
  },
  {
    id: 'UXVlc3Rpb246NDk3',
    __typename: 'SimpleQuestion',
    title: "De quelle couleur est le cheval blanc d'Henry IV ?",
    number: 3,
    private: false,
    hidden: false,
    position: 152,
    required: true,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'textarea',
  },
  {
    id: 'UXVlc3Rpb246NTAw',
    __typename: 'SimpleQuestion',
    title: 'Petit du loup ?',
    number: 4,
    private: false,
    hidden: false,
    position: 153,
    required: true,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'editor',
  },
  {
    id: 'UXVlc3Rpb246NDk5',
    __typename: 'SimpleQuestion',
    title: "Combien j'ai de doigt ?",
    number: 5,
    private: false,
    hidden: false,
    position: 154,
    required: true,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'number',
  },
  {
    id: 'UXVlc3Rpb246NTAx',
    __typename: 'MediaQuestion',
    title: 'Envoie ton CV',
    number: 6,
    private: false,
    hidden: false,
    position: 155,
    required: true,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'medias',
  },
  {
    id: 'UXVlc3Rpb246NTAy',
    __typename: 'MultipleChoiceQuestion',
    title: 'Coche la case vert',
    number: 7,
    private: false,
    hidden: false,
    position: 156,
    required: true,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'button',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 3,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTFmZjUwZWQtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Je suis vert',
            description: null,
            color: 'SUCCESS',
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTFmZjU1MGItNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Je suis orange',
            description: null,
            color: 'WARNING',
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6OTFmZjU4NTYtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Je suis rouge',
            description: null,
            color: 'DANGER',
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NTAz',
    __typename: 'MultipleChoiceQuestion',
    title: 'Qui a dit "Je suis ton père" ?',
    number: 8,
    private: false,
    hidden: false,
    position: 157,
    required: true,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'radio',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 3,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YWIyZTZmNjAtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Yoda',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YWIyZTczYzAtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Dark Vador',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YWIyZTc2ZDktNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Jean pierre Foucault',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NTA0',
    __typename: 'MultipleChoiceQuestion',
    title: 'Tes sports préférés ?',
    number: 9,
    private: false,
    hidden: false,
    position: 158,
    required: true,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'checkbox',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 4,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGFiNTQtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Tennis',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGFmYTUtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Canoë Kayak',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGIzMDQtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Golf',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGI2MTMtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Football',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NTA1',
    __typename: 'MultipleChoiceQuestion',
    title: 'Fruits préférés ?',
    number: 10,
    private: false,
    hidden: false,
    position: 159,
    required: true,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'ranking',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 3,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6ZDUzZWJhMmItNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Pomme',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6ZDUzZWJkZjctNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Poire',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6ZDUzZWMxMWUtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA2',
            title: 'Fraise',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NDk10',
    __typename: 'SimpleQuestion',
    title: 'Combien de pouce ?',
    number: 11,
    private: false,
    hidden: false,
    position: 160,
    required: true,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'number',
  },
  {
    id: 'UXVlc3Rpb246NTA90',
    __typename: 'MultipleChoiceQuestion',
    title: 'Veuillez sélectionner 2 fruits',
    number: 12,
    private: false,
    hidden: false,
    position: 161,
    required: true,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'checkbox',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: { type: 'EQUAL', number: 2 },
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 3,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGFiNTQtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA12',
            title: 'Pomme',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGFiNTQtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA13',
            title: 'Poire',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGFiNTQtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA14',
            title: 'Football',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NTA91',
    __typename: 'MultipleChoiceQuestion',
    title: 'Veuillez sélectionner au moins 2 fruits',
    number: 12,
    private: false,
    hidden: false,
    position: 161,
    required: true,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'checkbox',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: { type: 'MIN', number: 2 },
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 3,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGFiNTQtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA15',
            title: 'Pomme',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGFiNTQtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA16',
            title: 'Poire',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGFiNTQtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA17',
            title: 'Banane',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NTA92',
    __typename: 'MultipleChoiceQuestion',
    title: 'Veuillez sélectionner maximum 1 fruit',
    number: 12,
    private: false,
    hidden: false,
    position: 161,
    required: true,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'checkbox',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: { type: 'MAX', number: 1 },
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 3,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGFiNTQtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA18',
            title: 'Pomme',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGFiNTQtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA19',
            title: 'Poire',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGFiNTQtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA20',
            title: 'Banane',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NTA93',
    __typename: 'MultipleChoiceQuestion',
    title: 'Veuillez inscrire votre fruit préféré',
    number: 13,
    private: false,
    hidden: false,
    position: 161,
    required: true,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'checkbox',
    isOtherAllowed: true,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 3,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGFiNTQtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA18',
            title: 'Pomme',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGFiNTQtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA19',
            title: 'Poire',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6YzYyMGFiNTQtNmQwOS0xMWVhLTlkNzItMDI0MmFjMTEwMDA20',
            title: 'Banane',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246NTA94',
    __typename: 'MajorityQuestion',
    title: 'Comment vas-tu ?',
    number: 11,
    private: false,
    hidden: false,
    position: 160,
    required: true,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'majority',
    randomQuestionChoices: false,
    validationRule: null,
  },
];

export const allTypeResponses: ResponsesInReduxForm = [
  {
    question: 'UXVlc3Rpb246NDg3',
    value: {
      value: 'Paris',
      label: 'Paris',
    },
  },
  {
    question: 'UXVlc3Rpb246NDk4',
    value: 'Bien',
  },
  {
    question: 'UXVlc3Rpb246NDk3',
    value: 'Blanc',
  },
  {
    question: 'UXVlc3Rpb246NTAw',
    value: '<p>Louveteau</p>',
  },
  {
    question: 'UXVlc3Rpb246NDk5',
    value: '10',
  },
  {
    question: 'UXVlc3Rpb246NTAx',
    value: [
      {
        id: '3de332be-6d0a-11ea-9d72-0242ac110006',
        name: 'randomImage.jpg',
        size: '17.5 Ko',
        url:
          'https://demo.cap-collectif.com/media/default/0001/01/40dacc5a6c1bbf642d7b41728632cfa3d50f0edb.jpeg',
      },
    ],
  },
  {
    question: 'UXVlc3Rpb246NTAy',
    value: 'Je suis vert',
  },
  {
    question: 'UXVlc3Rpb246NTAz',
    value: {
      labels: ['Dark Vador'],
      other: null,
    },
  },
  {
    question: 'UXVlc3Rpb246NTA0',
    value: {
      labels: ['Tennis', 'Football'],
      other: null,
    },
  },
  {
    question: 'UXVlc3Rpb246NTA1',
    value: ['Pomme', 'Poire', 'Fraise'],
  },
  {
    question: 'UXVlc3Rpb246NTA2',
    value: '2',
  },
];

export const allTypeResponsesWithError: ResponsesInReduxForm = [
  {
    question: 'UXVlc3Rpb246NDg3',
    value: null,
  },
  {
    question: 'UXVlc3Rpb246NDk4',
    value: null,
  },
  {
    question: 'UXVlc3Rpb246NDk3',
    value: null,
  },
  {
    question: 'UXVlc3Rpb246NTAw',
    value: '</p>',
  },
  {
    question: 'UXVlc3Rpb246NDk5',
    value: null,
  },
  {
    question: 'UXVlc3Rpb246NTAx',
    value: [],
  },
  {
    question: 'UXVlc3Rpb246NTAy',
    value: null,
  },
  {
    question: 'UXVlc3Rpb246NTAz',
    value: {
      labels: [],
      other: null,
    },
  },
  {
    question: 'UXVlc3Rpb246NTA0',
    value: {
      labels: [],
      other: null,
    },
  },
  {
    question: 'UXVlc3Rpb246NTA1',
    value: [],
  },
  {
    question: 'UXVlc3Rpb246NDk10',
    value: 'e-10',
  },
  {
    question: 'UXVlc3Rpb246NTA90',
    value: {
      labels: ['Pomme', 'Poire', 'Football'],
      other: null,
    },
  },
  {
    question: 'UXVlc3Rpb246NTA91',
    value: {
      labels: ['Pomme'],
      other: null,
    },
  },
  {
    question: 'UXVlc3Rpb246NTA92',
    value: {
      labels: ['Pomme', 'Poire'],
      other: null,
    },
  },
  {
    question: 'UXVlc3Rpb246NTA94',
    value: null,
  },
];

export const manyJumpAndOneAlwaysJump: Questions = [
  {
    id: 'UXVlc3Rpb246Mjg=',
    __typename: 'MultipleChoiceQuestion',
    title: 'Question 1',
    number: 1,
    private: false,
    hidden: false,
    position: 6,
    required: false,
    helpText: null,
    jumps: [
      {
        id: '43fb38af-6d25-11ea-bdfe-0242ac110004',
        origin: {
          id: 'UXVlc3Rpb246Mjg=',
        },
        destination: {
          id: 'UXVlc3Rpb246MzA=',
          title: 'Sesame',
          number: 3,
        },
        conditions: [
          {
            id: '43fb403e-6d25-11ea-bdfe-0242ac110004',
            operator: 'IS',
            question: {
              id: 'UXVlc3Rpb246Mjg=',
              title: 'Question 1',
              type: 'select',
            },
            value: {
              id: 'UXVlc3Rpb25DaG9pY2U6MTVlZWIxMzktNmQyNS0xMWVhLWJkZmUtMDI0MmFjMTEwMDA0',
              title: 'Sesame affiche toi',
            },
          },
        ],
      },
      {
        id: '43fb4433-6d25-11ea-bdfe-0242ac110004',
        origin: {
          id: 'UXVlc3Rpb246Mjg=',
        },
        destination: {
          id: 'UXVlc3Rpb246Mjk=',
          title: 'Là',
          number: 4,
        },
        conditions: [
          {
            id: '43fb47e1-6d25-11ea-bdfe-0242ac110004',
            operator: 'IS',
            question: {
              id: 'UXVlc3Rpb246Mjg=',
              title: 'Question 1',
              type: 'select',
            },
            value: {
              id: 'UXVlc3Rpb25DaG9pY2U6MTVlZWI1NTgtNmQyNS0xMWVhLWJkZmUtMDI0MmFjMTEwMDA0',
              title: 'Toi aussi',
            },
          },
        ],
      },
    ],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: {
      id: 'UXVlc3Rpb246MzE=',
      title: 'Question 2',
      number: 2,
    },
    description: null,
    type: 'select',
    isOtherAllowed: false,
    randomQuestionChoices: false,
    validationRule: null,
    choices: {
      pageInfo: {
        hasNextPage: false,
      },
      totalCount: 3,
      edges: [
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6MTVlZWIxMzktNmQyNS0xMWVhLWJkZmUtMDI0MmFjMTEwMDA0',
            title: 'Sesame affiche toi',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6MTVlZWI1NTgtNmQyNS0xMWVhLWJkZmUtMDI0MmFjMTEwMDA0',
            title: 'Toi aussi',
            description: null,
            color: null,
            image: null,
          },
        },
        {
          node: {
            id: 'UXVlc3Rpb25DaG9pY2U6MTVlZWI4ZDYtNmQyNS0xMWVhLWJkZmUtMDI0MmFjMTEwMDA0',
            title: 'Nothing',
            description: null,
            color: null,
            image: null,
          },
        },
      ],
    },
  },
  {
    id: 'UXVlc3Rpb246MzE=',
    __typename: 'SimpleQuestion',
    title: 'Question 2',
    number: 2,
    private: false,
    hidden: false,
    position: 7,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'text',
  },
  {
    id: 'UXVlc3Rpb246MzA=',
    __typename: 'SimpleQuestion',
    title: 'Sesame',
    number: 3,
    private: false,
    hidden: false,
    position: 8,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'text',
  },
  {
    id: 'UXVlc3Rpb246Mjk=',
    __typename: 'SimpleQuestion',
    title: 'Là',
    number: 4,
    private: false,
    hidden: false,
    position: 9,
    required: false,
    helpText: null,
    jumps: [],
    destinationJumps: [],
    alwaysJumpDestinationQuestion: null,
    description: null,
    type: 'text',
  },
];
