<?php

namespace Capco\UserBundle\Controller;

use Sonata\UserBundle\Controller\RegistrationFOSUser1Controller as BaseController;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;



/**
 * @Route("/register", defaults={"_feature_flag" = "registration"})
 */
class RegistrationController extends BaseController
{
    /**
     * @Route("/", name="capco_user_register")
     * @Template()
     */
    public function registerAction()
    {
        return parent::registerAction(); // TODO: Change the autogenerated stub
    }

}
