#!/bin/bash

if grep -i "^users" /etc/group; then
  groupdel users
fi

if ! grep -i "^docker" /etc/group; then
  echo "Adding docker group with gid: " $DOCKER_GID
  groupadd --gid=$DOCKER_GID docker && usermod -a -G docker,capco capco
fi

mkdir -m 777 -p /var/www/var
chown -R capco:capco /var/www/var
chown -R capco:capco /var/www/web/export

function test_mysqldatabase {
  mysql -h "${SYMFONY_DATABASE_HOST}" -uroot symfony > /dev/null
}

function test_redis {
  redis-cli -h "${SYMFONY_REDIS_HOST}" PING > /dev/null
}

# Wait till mysql and redis are ready
count=0
until ( test_mysqldatabase && test_redis )
do
  ((count++))
  if [ ${count} -gt 50 ]; then
    echo "Mysql and redis didn't become ready in time"
    exit 1
  fi
  sleep 0.1
  echo "Waiting"
done

while ! curl http://127.0.0.1:15672 > /dev/null 2>&1;
  do sleep 0.1
  echo "Waiting for rabbitmq to boot..."
done

exec /usr/sbin/php-fpm7.1 -y /etc/service/php-fpm/fpm.conf -O
