#!/bin/bash
set -e

function test_phpfpm {
  /etc/init.d/php7.1-fpm status > /dev/null
}

function test_mysqldatabase {
  mysql --host=127.0.0.1 -uroot symfony > /dev/null
}

echo "[$(date -u)][CRONTAB] Waiting for php-fpm and MySQL..."
# Wait till mysql and php-fpm are ready
until ( test_phpfpm && test_mysqldatabase )
do
  sleep 0.1
done

# remove write permission for (g)roup and (o)ther (required by cron)
chmod -R go-w /etc/cron.d

# update default values of PAM environment variables (used by CRON scripts)
env | while read -r LINE; do
    IFS="=" read VAR VAL <<< ${LINE}
    sed --in-place "/^${VAR}[[:blank:]=]/d" /etc/security/pam_env.conf || true
    echo "${VAR} DEFAULT=\"${VAL}\"" >> /etc/security/pam_env.conf
done

echo "[$(date -u)][CRONTAB] Installing…"
crontab -uroot /etc/cron.d/crontab

echo "[$(date -u)][CRONTAB] Started!"
exec cron -f
