#!/bin/bash

if [[ -f /app.env ]]
then
    # app.env exists, source it
    . /app.env
else
    # app.env does not exist
    # it is a cluster instance
    CAPCO_CRON_COMPUTE_PHP_MEMORY_LIMIT=$(cat /config/CAPCO_CRON_COMPUTE_PHP_MEMORY_LIMIT)
    CAPCO_CRON_EXPORT_PHP_MEMORY_LIMIT=$(cat /config/CAPCO_CRON_EXPORT_PHP_MEMORY_LIMIT)
    SLACK_WEBHOOK_ANTIVIRUS=$(cat /secrets/SLACK_WEBHOOK_ANTIVIRUS)
fi
