SourceCategory:
    type: object
    config:
        description: 'A source category.'
        fields:
            id:
                type: 'ID!'
            title:
                type: 'String!'
            isEnabled:
                type: 'Boolean!'
                description: 'Whether the source category is published.'
            createdAt:
                type: 'DateTime!'
            updatedAt:
                type: 'DateTime!'
