CreatePresentationProjectTabInput:
    type: relay-mutation-input
    config:
        description: 'Input of createPresentationProjectTab mutation.'
        fields:
            projectId:
                type: 'ID!'
            title:
                type: 'String!'
            slug:
                type: 'String!'
            enabled:
                type: 'Boolean!'
            body:
                type: 'String'
