CreateEventsProjectTabInput:
    type: relay-mutation-input
    config:
        description: 'Input of createEventsProjectTab mutation.'
        fields:
            projectId:
                type: 'ID!'
            title:
                type: 'String!'
            slug:
                type: 'String!'
            enabled:
                type: 'Boolean!'
            eventItems:
                type: '[ProjectTabEventItemInput!]'
