UpdateNewsProjectTabInput:
    type: relay-mutation-input
    config:
        description: 'Input of updateNewsProjectTab mutation.'
        fields:
            tabId:
                type: 'ID!'
            title:
                type: 'String!'
            slug:
                type: 'String!'
            enabled:
                type: 'Boolean!'
            newsItems:
                type: '[ProjectTabNewsItemInput!]'
