#!/bin/bash

function test_phpfpm {
  /etc/init.d/php7.4-fpm status > /dev/null
}

function test_mysqldatabase {
  mysqlshow --host=${SYMFONY_DATABASE_HOST} --port=${SYMFONY_DATABASE_PORT:-3306} -uroot symfony > /dev/null
}

# Wait till mysql and php-fpm are ready
until ( test_phpfpm && test_mysqldatabase )
do
  sleep 0.1
done

echo "Installing crontab..."
crontab /etc/cron.d/crontab

echo "[CRON] Crontab installed"
exec cron -f
