#!/bin/bash

echo "[$(date -u)][NODEJS] Started!"

cd /var/www/admin-next

# Make sure to run the following command are already executed 
# in the admin-next directory :
# - yarn install
# - yarn relay


if [[ -n "$CI" ]]; then
    # Launch `/admin-next` only for cypress tests
    if [[ "$CIRCLE_JOB" == *"cypress"* ]]; then
        exec pm2 start --no-daemon bash --name "admin-next" -- -lc "yarn local-build-and-serve"
    else
        exec sleep 10
    fi
fi
