<?php

namespace Capco\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArgumentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArgumentRepository extends EntityRepository
{
    /**
     * Get all enabled arguments by type and opinion, sorted by argumentSort.
     */

    /**
     * @param $type
     * @param $opinion
     * @param null $argumentSort
     *
     * @return array
     */
    public function getByTypeAndOpinionOrderedJoinUserReports($type, $opinion, $argumentSort = null, $user = null)
    {
        $qb = $this->getIsEnabledQueryBuilder()
            ->addSelect('aut', 'm', 'v', 'r')
            ->leftJoin('a.Author', 'aut')
            ->leftJoin('aut.Media', 'm')
            ->leftJoin('a.Votes', 'v')
            ->leftJoin('a.Reports', 'r', 'WITH', 'r.Reporter =  :user')
            ->andWhere('a.isTrashed = :notTrashed')
            ->andWhere('a.opinion = :opinion')
            ->andWhere('a.type = :type')
            ->setParameter('notTrashed', false)
            ->setParameter('opinion', $opinion)
            ->setParameter('type', $type)
            ->setParameter('user', $user);

        if (null != $argumentSort) {
            if ($argumentSort == 'popularity') {
                $qb->orderBy('a.voteCount', 'DESC');
            } elseif ($argumentSort == 'date') {
                $qb->orderBy('a.updatedAt', 'DESC');
            }
        }

        $qb->addOrderBy('a.updatedAt', 'DESC');

        return $qb->getQuery()
            ->getResult();
    }

    /**
     * Find all arguments by consultation.
     *
     * @param $consultation
     *
     * @return array
     */
    public function getByConsultation($consultation)
    {
        $qb = $this->createQueryBuilder('a')
            ->addSelect('o', 'ot', 'aut')
            ->leftJoin('a.opinion', 'o')
            ->leftJoin('o.OpinionType', 'ot')
            ->leftJoin('o.Author', 'aut')
            ->andWhere('o.Consultation = :consultation')
            ->setParameter('consultation', $consultation)
            ->addOrderBy('a.updatedAt', 'DESC');

        return $qb->getQuery()
            ->getResult();
    }

    /**
     * Get one argument by id, opinion, opinion type and consultation.
     *
     * @param $consultation
     * @param $opinionType
     * @param $opinion
     * @param $argument
     *
     * @return mixed
     *
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getOneById($consultation, $opinionType, $opinion, $argument)
    {
        return $this->getIsEnabledQueryBuilder()
            ->addSelect('aut', 'm', 'v', 'o', 'c', 'ot')
            ->leftJoin('a.Author', 'aut')
            ->leftJoin('aut.Media', 'm')
            ->leftJoin('a.Votes', 'v')
            ->leftJoin('a.opinion', 'o')
            ->leftJoin('o.Consultation', 'c')
            ->leftJoin('o.OpinionType', 'ot')
            ->andWhere('a.id = :argument')
            ->andWhere('o.slug = :opinion')
            ->andWhere('c.slug = :consultation')
            ->andWhere('ot.slug = :opinionType')
            ->setParameter('argument', $argument)
            ->setParameter('opinion', $opinion)
            ->setParameter('consultation', $consultation)
            ->setParameter('opinionType', $opinionType)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * Get all trashed arguments for consultation.
     *
     * @param $consultation
     *
     * @return mixed
     */
    public function getTrashedByConsultation($consultation)
    {
        return $this->getIsEnabledQueryBuilder()
            ->addSelect('o', 'v', 'aut', 'm')
            ->leftJoin('a.opinion', 'o')
            ->leftJoin('a.Votes', 'v')
            ->leftJoin('o.Author', 'aut')
            ->leftJoin('aut.Media', 'm')
            ->andWhere('a.isTrashed = :trashed')
            ->andWhere('o.Consultation = :consultation')
            ->setParameter('trashed', true)
            ->setParameter('consultation', $consultation)
            ->orderBy('a.trashedAt', 'DESC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Count all arguments by user.
     *
     * @param $user
     *
     * @return mixed
     */
    public function countByUser($user)
    {
        $qb = $this->getIsEnabledQueryBuilder()
            ->select('COUNT(a) as TotalArguments')
            ->leftJoin('a.opinion', 'o')
            ->leftJoin('o.Consultation', 'c')
            ->andWhere('a.Author = :author')
            ->andWhere('o.isEnabled = :enabled')
            ->andWhere('c.isEnabled = :enabled')
            ->setParameter('author', $user)
            ->setParameter('enabled', true);

        return $qb
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * Get all arguments by user.
     *
     * @param $user
     *
     * @return mixed
     */
    public function getByUser($user)
    {
        return $this->getIsEnabledQueryBuilder()
            ->leftJoin('a.opinion', 'o')
            ->addSelect('o')
            ->leftJoin('o.Consultation', 'c')
            ->addSelect('c')
            ->leftJoin('o.Author', 'aut')
            ->addSelect('aut')
            ->leftJoin('aut.Media', 'm')
            ->addSelect('m')
            ->leftJoin('a.Votes', 'v')
            ->addSelect('v')
            ->andWhere('a.Author = :author')
            ->setParameter('author', $user)
            ->andWhere('o.isEnabled = :enabled')
            ->setParameter('enabled', true)
            ->andWhere('c.isEnabled = :consultEnabled')
            ->setParameter('consultEnabled', true)
            ->getQuery()
            ->getResult();
    }

    protected function getIsEnabledQueryBuilder()
    {
        return $this->createQueryBuilder('a')
            ->andWhere('a.isEnabled = :isEnabled')
            ->setParameter('isEnabled', true);
    }
}
