<?php

namespace Capco\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * OpinionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpinionTypeRepository extends EntityRepository
{
    public function findByType($consultation, $offset = 0, $limit = 10)
    {
        $qb = $this->createQueryBuilder('ot')
            ->leftJoin('ot.Opinions','o')
            ->addSelect('o')
            ->leftJoin('o.Problem', 'p')
            ->addSelect('p')
            ->leftJoin('o.Consultation', 'c')
            ->addSelect('c')
            ->leftJoin('o.Author', 'a')
            ->addSelect('a')
            ->andWhere('o.Consultation = :consultation')
            ->setParameter('consultation', $consultation)
            ->orderBy('ot.position', 'DESC')
            ->orderBy('o.createdAt', 'DESC');

        if ($limit) {
            $qb->setMaxResults($limit);
        }

        if ($offset) {
            $qb->setFirstResult($offset);
        }

        return $qb
            ->getQuery()
            ->getResult();
    }

//    public function getOpinionWithConsultation($consultation, $slug)
//    {
//        $qb = $this->createQueryBuilder('ot')
//            ->leftJoin('ot.Opinions','o')
//            ->addSelect('o')
//            ->leftJoin('o.Consultation', 'c')
//            ->addSelect('c')
//            ->andWhere('o.Consultation = :consultation')
//            ->setParameter('consultation', $consultation)
//            ->andWhere('ot.slug = :slug')
//            ->setParameter('slug', $slug)
//            ->orderBy('ot.position', 'ASC');
//
//        return $qb
//            ->getQuery()
//            ->getResult();
//    }

}
