<?php

namespace Capco\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * OpinionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpinionRepository extends EntityRepository
{
    //Récupère toutes les opinions par Type d'une consultation, avec la possibilité de définir un offset et un limit
    public function getOpinionsByType($opinionType_slug, $offset = 1, $limit = 10)
    {
        $qb = $this->createQueryBuilder('o')
            ->leftJoin('o.OpinionType', 'ot')
            ->addSelect('ot')
            ->leftJoin('o.Consultation', 'c')
            ->addSelect('c')
            ->leftJoin('o.Author', 'a')
            ->addSelect('a')
//            ->andWhere('c.slug = :slug')
//            ->setParameter('slug', $consultation)
            ->andWhere('ot.slug = :opinionType_slug')
            ->setParameter('opinionType_slug', $opinionType_slug)
            ->orderBy('o.createdAt', 'DESC');

        if ($limit) {
            $qb->setMaxResults($limit);
        }

        if ($offset) {
            $qb->setFirstResult($offset);
        }

        return $qb
            ->getQuery()
            ->getResult();
    }
}
