<?php

namespace Capco\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * OpinionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProblemRepository extends EntityRepository
{
    public function getWithArguments($problem)
    {
        $qb = $this->createQueryBuilder('p')
                ->leftJoin('p.arguments', 'arg')
                ->addSelect('arg')
                ->leftJoin('p.Author', 'a')
                ->addSelect('a')
                ->leftJoin('arg.Author', 'aArg')
                ->addSelect('aArg')
                ->leftJoin('arg.contribution', 'aCont')
                ->addSelect('aCont')
                ->andWhere('p.slug = :problem')
                ->setParameter('problem', $problem);

        return $qb->getQuery()
            ->getOneOrNullResult();

    }
}
