<?php

namespace Capco\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * OpinionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProblemTypeRepository extends EntityRepository
{
    public function findByType($consultation)
    {
        $qb = $this->createQueryBuilder('pt')
            ->leftJoin('pt.Problems','p')
            ->addSelect('p')
            ->leftJoin('p.Author', 'a')
            ->addSelect('a')
            ->leftJoin('p.arguments', 'arg')
            ->addSelect('arg')
            ->leftJoin('p.Consultation', 'c')
            ->addSelect('c')
            ->andWhere('p.Consultation = :consultation')
            ->setParameter('consultation', $consultation)
            ->orderBy('p.createdAt', 'DESC');

        return $qb
            ->getQuery()
            ->getResult();
    }

}
