<?php

namespace Capco\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * SourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceRepository extends EntityRepository
{
    public function getTrashedSourcesByConsultation($consultation)
    {
        $qb = $this->createQueryBuilder('s')
            ->andWhere('s.isEnabled = :enabled')
            ->setParameter('enabled', true)
            ->andWhere('s.isTrashed = :trashed')
            ->setParameter('trashed', true)
            ->leftJoin('s.Category', 'ca')
            ->addSelect('ca')
            ->leftJoin('s.Opinion', 'o')
            ->addSelect('o')
            ->leftJoin('s.Author', 'aut')
            ->addSelect('aut')
            ->leftJoin('aut.Media', 'm')
            ->addSelect('m')
            ->andWhere('o.Consultation = :consultation')
            ->setParameter('consultation', $consultation)
            ->orderBy('s.trashedAt', 'DESC');

        return $qb->getQuery()->getResult();

    }

    public function getEnabledSourcesByOpinion($opinion)
    {
        $qb = $this->createQueryBuilder('s')
            ->andWhere('s.isEnabled = :enabled')
            ->setParameter('enabled', true)
            ->andWhere('s.isTrashed = :notTrashed')
            ->setParameter('notTrashed', false)
            ->leftJoin('s.Category', 'ca')
            ->addSelect('ca')
            ->leftJoin('s.Opinion', 'o')
            ->addSelect('o')
            ->leftJoin('s.Author', 'aut')
            ->addSelect('aut')
            ->leftJoin('aut.Media', 'm')
            ->addSelect('m')
            ->andWhere('s.Opinion = :opinion')
            ->setParameter('opinion', $opinion)
            ->orderBy('s.updatedAt', 'DESC');

        return $qb->getQuery()->getResult();

    }

}
