<?php

namespace Capco\AppBundle\Repository;

use Capco\AppBundle\Entity\CollectStep;
use Doctrine\ORM\EntityRepository;

/**
 * StatusRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends EntityRepository
{

    public function getByCollectStep(CollectStep $step)
    {
        $qb = $this->createQueryBuilder('s')
            ->where('s.step = :step')
            ->setParameter('step', $step)
            ->orderBy('s.position', 'ASC')
        ;

        return $qb->getQuery()->getResult();
    }
    
}
