<?php

namespace Capco\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * OpinionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends EntityRepository
{

    public function getVotesByValue($opinion, $value = 1)
    {
        $qb = $this->createQueryBuilder('v')
                ->select('COUNT(v) as VoteCount')
                ->leftJoin('v.Contribution', 'c')
                ->addSelect('c.slug')
                ->andWhere('c.slug = :opinion')
                ->setParameter('opinion', $opinion)
                ->andWhere('v.value = :value')
                ->setParameter('value', $value);

        return $qb->getQuery()
            ->getResult();
    }
}
