#!/bin/bash

# Configure Redis
sed -i 's/^\(bind .*\)$/# \1/' /etc/redis/redis.conf
sed -i 's/^\(daemonize .*\)$/# \1/' /etc/redis/redis.conf
sed -i 's/^\(dir .*\)$/# \1\ndir \/data/' /etc/redis/redis.conf
sed -i 's/^\(logfile .*\)$/# \1/' /etc/redis/redis.conf

exec /usr/bin/redis-server /etc/redis/redis.conf
