services:
    _defaults:
        autowire: true
        autoconfigure: true

    Capco\Manager\RepositoryManager:
        calls:
            - method: setRepositories
              arguments:
                  - !tagged_iterator repository.manager
