#!/bin/bash

echo "Checking if elasticsearch is booted..."
while ! curl http://localhost:9200 > /dev/null 2>&1;
  do sleep 0.1
  echo "Waiting for elasticsearch to boot..."
done
echo "Elasticsearch is up"

# Increasing memory_limit is required when importing a lot of content
su capco -c "php -d memory_limit=512M bin/console fos:elastica:populate --env=prod --no-interaction"

if [ $? -eq 1 ]; then
  echo "Populating the index failed... Exiting" >&2
  exit 1
fi

echo "Index has been populated !"
