#!/bin/bash

rm -f /etc/php5/*/conf.d/newrelic.ini

mkdir -p /var/www/app/cache
mkdir -p /var/www/app/logs
mkdir -p /var/www/web/bundles
chmod -R 777 /var/www/app/cache /var/www/app/logs /var/www/web/media /var/www/web/bundles

echo "Clearing previous cache..."
rm -rf /var/www/app/cache/*

# Wait till mysql is booted
while ! mysql --host=127.0.0.1 > /dev/null 2>&1; do sleep 1; done

echo "Mysql has booted - Running database migrations."

su capco <<'EOF'

cd /var/www

# Migrate existing database or create one with default data
RESULT=`php app/console doctrine:migrations:status --env=prod 2>&1 | grep -o "Unknown database" | wc -l`
if [ "$RESULT" != "0" ]; then
    php app/console doctrine:database:create --if-not-exists --env=prod --no-interaction
    php app/console doctrine:schema:create --env=prod --no-interaction
    php app/console doctrine:migrations:version --add --all --env=prod --no-interaction
    php app/console capco:load-base-data --force --env=prod --no-interaction
else
    php app/console doctrine:migrations:migrate --env=prod --no-interaction
fi

php app/console cache:warmup --env=prod --no-interaction
php app/console assets:install --symlink --env=prod --no-interaction

# Wait till elasticsearch is booted
while ! curl http://localhost:9200 > /dev/null 2>&1; do sleep 1; done

echo "Elasticsearch has booted - Populating index."
php app/console fos:elastica:populate --env=prod --no-interaction &

EOF

exec php5-fpm -y /etc/service/php-fpm/fpm.conf -O
