#!/bin/bash

echo "Updating rabbitmq vhost to match schema..."
su capco -c "php bin/rabbit vhost:mapping:create --password=guest app/config/rabbitmq.yml"

echo "Starting rabbitmq consumers..."

su capco -c "php bin/console swarrot:consume:proposal_create proposal_create --env=prod --requeue-on-error &"
su capco -c "php bin/console swarrot:consume:proposal_update proposal_update --env=prod &"
su capco -c "php bin/console swarrot:consume:proposal_delete proposal_delete --env=prod &"
