#!/bin/bash

while ! curl http://localhost:5672 > /dev/null 2>&1;
  do sleep 1
  echo "Waiting for rabbitmq to boot..."
done
echo "Starting rabbitmq consumers..."

su capco -c "php bin/console swarrot:consume:proposal_create proposal_create --env=prod --requeue-on-error &"
su capco -c "php bin/console swarrot:consume:proposal_update proposal_update --env=prod &"
su capco -c "php bin/console swarrot:consume:proposal_delete proposal_delete --env=prod &"
