#!/bin/bash

echo "Starting rabbitmq consumers..."

su capco -c "php bin/console swarrot:consume:proposal_create proposal_create --env=prod --requeue-on-error &"
su capco -c "php bin/console swarrot:consume:proposal_update proposal_update --env=prod --requeue-on-error &"
su capco -c "php bin/console swarrot:consume:proposal_delete proposal_delete --env=prod --requeue-on-error &"
su capco -c "php bin/console swarrot:consume:comment_create comment_create --env=prod --requeue-on-error &"
su capco -c "php bin/console swarrot:consume:comment_update comment_update --env=prod --requeue-on-error &"
su capco -c "php bin/console swarrot:consume:comment_delete comment_delete --env=prod --requeue-on-error &"

echo "Rabbitmq consumers are up!"
