UpdateAppearanceColorPayload:
    type: relay-mutation-payload
    config:
        fields:
            siteColor:
                type: 'InternalSiteColor'
            errorCode:
                type: 'UpdateAppearanceSettingErrorCode'
