#!/bin/bash

cd /var/www

echo "[$(date -u)][PHP-FPM] Creating var/ files..."
for directory in var/cache var/log var/logs public/bundles public/media/default public/media/sonata_category; do
  if [ ! -d "$directory" ]; then
    mkdir -p -m 777 $directory
    chown capco:capco $directory
  fi
done
echo "[PHP-FPM] Created var/ files!"

echo "[$(date -u)][PHP-FPM] Setting permissions to public/, cache/, log/ and logs/..."
chmod -R 777 public/media
chmod -R 777 var/logs
chmod -R 777 var/log
rm -rf var/cache/prod/*
chown -R capco:capco var/cache
chown -R capco:capco var/logs
chown -R capco:capco var/log
echo "[$(date -u)][PHP-FPM] Permissions gived to public/, cache/ and, log/ logs/!"

echo "[$(date -u)][PHP-FPM] Warming up cache and install bundle assets..."
chmod -R 777 var/ && chown -R capco:capco var/ 
gosu capco php bin/console cache:warmup --no-debug --env=prod --no-interaction --quiet
gosu capco php bin/console assets:install public --symlink --env=prod --no-interaction --quiet
echo "[$(date -u)][PHP-FPM] Cache warmed!"

echo "[$(date -u)][PHP-FPM] Started!"
exec /usr/sbin/php-fpm7.4 --fpm-config /etc/service/php-fpm/fpm.conf --force-stderr
