// @ts-nocheck
import { PolymorphicComponent } from '../../Ui/Primitives/AppBox'
import { ComponentProps } from 'react'

declare const ICON_NAME = {
  TRASH: 'TRASH',
  PENCIL: 'PENCIL',
  PENCIL_O: 'PENCIL_O',
  USER: 'USER',
  CLOCK_O: 'CLOCK_O',
  CLOCK: 'CLOCK',
  CALENDAR_O: 'CALENDAR_O',
  CALENDAR: 'CALENDAR',
  ARROW_LEFT_O: 'ARROW_LEFT_O',
  ARROW_RIGHT_O: 'ARROW_RIGHT_O',
  ARROW_DOWN_O: 'ARROW_DOWN_O',
  ARROW_UP_O: 'ARROW_UP_O',
  ARROW_LEFT: 'ARROW_LEFT',
  ARROW_RIGHT: 'ARROW_RIGHT',
  ARROW_DOWN: 'ARROW_DOWN',
  ARROW_UP: 'ARROW_UP',
  ADD: 'ADD',
  CROSS: 'CROSS',
  CIRCLE_INFO: 'CIRCLE_INFO',
  CIRCLE_ALERT: 'CIRCLE_ALERT',
  CIRCLE_CHECK: 'CIRCLE_CHECK',
  CIRCLE_CROSS: 'CIRCLE_CROSS',
  CHECK_O: 'CHECK_O',
  DOWNLOAD: 'DOWNLOAD',
  NEWSPAPER: 'NEWSPAPER',
  SPINNER: 'SPINNER',
  BELL: 'BELL',
  THUMB_UP: 'THUMB_UP',
  THUMB_UP_O: 'THUMB_UP_O',
  THUMB_DOWN: 'THUMB_DOWN',
  LONG_ARROW_LEFT: 'LONG_ARROW_LEFT',
  LONG_ARROW_RIGHT: 'LONG_ARROW_RIGHT',
  FLAG: 'FLAG',
  MORE: 'MORE',
  MODERATE: 'MODERATE',
  HYPERLINK: 'HYPERLINK',
  BUBBLE_O: 'BUBBLE_O',
  USER_O: 'USER_O',
  PIN_O: 'PIN_O',
  FOLDER_O: 'FOLDER_O',
  BOOK_STAR_O: 'BOOK_STAR_O',
  PREVIEW: 'PREVIEW',
  FACEBOOK: 'FACEBOOK',
  ENVELOPE: 'ENVELOPE',
  LINK: 'LINK',
  LINKEDIN: 'LINKEDIN',
  TWITTER: 'TWITTER',
  DRAG: 'DRAG',
  FILE_O: 'FILE_O',
  FILE: 'FILE',
  COG_O: 'COG_O',
  ENVELOPE_O: 'ENVELOPE_O',
  LOCK: 'LOCK',
  PRINT: 'PRINT',
  PIE_CHART: 'PIE_CHART',
  ADD_DRAG: 'ADD_DRAG',
  SEARCH: 'SEARCH',
  SN_FACEBOOK: 'SN_FACEBOOK',
  SN_TWITTER: 'SN_TWITTER',
  SN_YOUTUBE: 'SN_YOUTUBE',
  SN_WEBPAGE: 'SN_WEBPAGE',
  SN_LINKEDIN: 'SN_LINKEDIN',
  SN_INSTAGRAM: 'SN_INSTAGRAM',
  ICON_PLACEHOLDER: 'ICON_PLACEHOLDER',
  DUPLICATE: 'DUPLICATE',
  DUPLICATE_O: 'DUPLICATE_O',
  IMAGE: 'IMAGE',
  ERROR: 'ERROR',
  SHARE: 'SHARE',
  EARTH: 'EARTH',
  SORT: 'SORT',
  ORGANISATION: 'ORGANISATION',
}

declare const ICON_SIZE = {
  XS: 'xs',
  SM: 'sm',
  MD: 'md',
  LG: 'lg',
  XL: 'xl',
  XXL: 'xxl',
}

declare const Icon: PolymorphicComponent<
  ComponentProps<SVGElement> & {
    name: keyof typeof ICON_NAME
    size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl' | string
    color?: string
  }
>

export default Icon
