VerifyParticipantPhoneNumberPayload:
    type: relay-mutation-payload
    config:
        fields:
            participant:
                type: 'InternalParticipant'
                description: 'The updated Participant.'
            errorCode:
                type: 'VerifySMSErrorCode'
                description: 'The error code, if failing.'
            reconciliationMode:
                type: 'PhoneReconciliationMode!'
                description: 'The reconciliation mode applied after phone verification.'
