ChangeProposalContentPayload:
    type: relay-mutation-payload
    config:
        fields:
            proposal:
                type: 'InternalProposal'
            shouldTriggerWorkflow:
                type: 'Boolean!'
                description: 'Whether the workflow should be triggered'
            userErrors:
                type: '[UserError!]'
                description: 'An unsuccessful mutation will return one or more `UserError` objects.'
