UpdateNewProjectPayload:
    type: relay-mutation-payload
    config:
        fields:
            project:
                type: 'InternalProject'
            errorCode:
                type: 'UpdateNewProjectErrorCode'
                description: 'Errors for updateNewProject mutation.'
