VerifyUserPhoneNumberPayload:
    type: relay-mutation-payload
    config:
        fields:
            user:
                type: 'InternalUser'
                description: 'The updated User.'
            errorCode:
                type: 'VerifySMSErrorCode'
                description: 'The error code, if failing.'
            reconciliationMode:
                type: 'PhoneReconciliationMode!'
                description: 'The reconciliation mode applied after phone verification.'
