DeleteHttpRedirectPayload:
    type: relay-mutation-payload
    config:
        fields:
            deletedRedirectId:
                type: 'ID'
                description: 'The deleted redirect ID.'
            errorCode:
                type: 'HttpRedirectErrorCode'
                description: 'The available errors if any.'
