NewsletterSubscriptionConnection:
    type: relay-connection
    config:
        nodeType: InternalNewsletterSubscription!
        connectionFields:
            totalCount:
                type: Int!
