#!/bin/bash

while [ ! -f /var/run/php7.1-fpm.pid ] > /dev/null 2>&1;
  do sleep 1
done

echo "Starting Supervisor..."
exec supervisord --configuration=/etc/supervisord/supervisord.conf --loglevel=warn
