#!/bin/bash

chown -R capco:capco /var/www/app/cache
chown -R capco:capco /var/www/app/logs

su capco <<'EOF'
sleep 5
cd       /var/www
php app/console doctrine:database:create
php app/console doctrine:schema:create
php app/console cache:warmup --env=prod --no-debug
EOF

exec php5-fpm -y /etc/service/php-fpm/fpm.conf -O
