DeleteFooterSocialNetworkPayload:
    type: relay-mutation-payload
    config:
        fields:
            deletedFooterSocialNetworkId:
                type: 'ID!'
                description: 'The deleted footer social network ID.'
